### ISSUE TITLE
Issues with JLPCB order/DFM Analysis

### ISSUE THREAD

**Issue by Torsdan** [stuartpittaway/diyBMSv4#101]
This is for the controller. Parts appear to be there and correct, though I'm unsure about the sdcard.
I just wish to check if this is normal or I'm doing something wrong.

I'm also having the issue where they are rotating the D2 on the modules, but I should be able to fix that myself. [#73](https://github.com/stuartpittaway/diyBMSv4/issues/73)

![image](https://user-images.githubusercontent.com/1498749/137330142-4f7c2d73-7eaf-4126-b1ad-863df11cf5d5.png)

**Comment by stuartpittaway** [comment]
As stock comes and goes at JLC they appear to keep updating the sizes of parts or the rotation.

I can't say for sure if what they have suggested is correct or not.

Are you using the original part numbers without substitution?

**Comment by Torsdan** [comment]
Just an update for posterity, contacted JLPCB, snippets from chat support:
![image](https://user-images.githubusercontent.com/1498749/137437695-ef328d34-e704-4d92-a8e7-e87544bc8a34.png)
![image](https://user-images.githubusercontent.com/1498749/137437719-782e28f4-0085-4b69-9123-de6de1bce9b4.png)
![image](https://user-images.githubusercontent.com/1498749/137437743-6344a201-4810-4c95-b279-959549ab7c2e.png)
