### ISSUE TITLE
O. O. S and C. R. C errors

### ISSUE THREAD

**Issue by DCGenerators** [stuartpittaway/diyBMSv4#107]
Hello.
New here!
Having the following issue with a newly installed setup of 16 * V4. 4 modules.
Trouble communicating with modules with OOS and crc errors.
Controller is an esp32 nodemcu
![Screenshot_20220217-193559_Remote Desktop](https://user-images.githubusercontent.com/99908204/154543732-02fc9352-500f-4ff1-8c08-f7d9eb6b04c1.jpg)

**Comment by stuartpittaway** [comment]
Ok, let's break this down a bit.

CRC errors are corruption in the signal between the controller and/or modules.

The OOS errors occur when a request is sent to the modules but no reply is ever received.

Judging by the bad packet count errors in the screen shot, I think there is a problem with the first module.

Can you swap that module with one of the others, see if the problem follows?

**Comment by stuartpittaway** [comment]
No response, so closing the issue, please feel free to open if you still have problems.a
