### ISSUE TITLE
ATTINY841 Substitute with ATTINY441 ?

### ISSUE THREAD

**Issue by mikeman400** [stuartpittaway/diyBMSv4#110]
Hi 
Since the ATTINY841doesn't seem to be available, could it be substituted with a ATTINY441-SSUR? I'm not sure if the firmware will be too large or require more ram than available on this chip. 

Thanks for all the hard work!

**Comment by mikeman400** [comment]
I was talking about using it on the 4.40 modules if that matters.

**Comment by fhorst1** [comment]
Please read :

https://www.avrfreaks.net/forum/attiny841-vs-441-vs-44a-and-other-questions

It's probably about the exact same issue (unless there are 2 open source
BMS with cell monitors :-). )

Or in a really short answer: doesn't work.
Probably a memory issue.

If soldering is an issue, you simply could let JLCPCB solder a socket.
Pricing of the 841 at JLC is usually already crazy expensive.

I got mine from different sources, usually half the price JLC asked for.

One site to find different vendors for the attini841:
https://octopart.com/attiny841-ssu-microchip-77762298

I'm afraid you are out of luck, the few sites I looked at had new stock in
march 2023 (next year)
Global chip shortage..... even the simple attiny!!

Good hunting!

**Comment by mikeman400** [comment]
Hmm.. Interesting link.  Seems like it should work but maybe the code could use some optimization? 

I'm asking because the ATTINY841 is not available, anywhere it seems.  Soldering is no issue but thanks for the suggestion. 

Thanks for the reply

**Comment by stuartpittaway** [comment]
Hi, I've not tried anything other than the 841, however is very difficult to find.

The code compiles to around 6k, so would be too large for the 441 unless optimization was made

**Comment by mikeman400** [comment]
>  The code compiles to around 6k
Thanks Stuart.   That's the piece of info I needed to know. 

Thank you for all you hard work and supporting the community.
