### ISSUE TITLE
Controller V4.4 - broken connection on VSPI_MOSI via

### ISSUE THREAD

**Issue by stuartpittaway** [stuartpittaway/diyBMSv4#116]
If you have recently ordered a PCB using Gerber files between 17th May and 23rd May 2022, then there is likely to be issues with LCD and memory card working correctly.

This is fixed in board version 76eb9368da7fb189570628f82d6a8c294260fbe8 which will be marked on the PCB with the silkscreen version of "revision c8f1403" (23 May 2022) 

To fix broken PCB's simply add a small wire between pin 1 on the 6 pin header (J8) and pin 2 of the LCD header (marked T_DO).

This is easy to do on the reverse of the PCB board, as shown in the picture.

![ControllerCircuit-bottom](https://user-images.githubusercontent.com/1201909/169826409-f05de1d1-b133-4060-a908-0bcee7718b30.png)

**Comment by javierolme** [comment]
Nice. Works for me.

**Comment by vietxtlife** [comment]
My SD card is not working too, the board i have is around 2 years old. Should i try this fix on it?

**Comment by stuartpittaway** [comment]
> My SD card is not working too, the board i have is around 2 years old. Should i try this fix on it?

No, there isn't any reporter issue with older boards. Just this particular revision.

I recommend using a low capacity and card like 1 or 2gb.
