### ISSUE TITLE
timer not working when triger value > reset value

### ISSUE THREAD

**Issue by smdbg** [stuartpittaway/diyBMSv4#118]
![12345](https://user-images.githubusercontent.com/41722268/170784276-c86c1858-0378-4f40-83af-82e08076e19a.jpg)
The goal is the timer to start at 23.00 and end in 6.00 next day.

**Comment by stuartpittaway** [comment]
Hello, unfortunately crossing daily boundaries isn't supported, the reset value needs to be greater than the trigger value.

You could use both timer 1 and timer 2.  

Timer covers between 23:00 and 23:59, and Timer 2 covers 00:00 to 06:00, both driving the same relay.
