### ISSUE TITLE
Can you add an "cpl" file?

### ISSUE THREAD

**Issue by ArchGalileu** [stuartpittaway/diyBMSv4#12]
Hello

I would like to try the JLPCB SMT service

Missing .cpl file to proceed.

Tried with kicad but can't view components on 3d view, also on export off cpl (csv) missing 

`No header row found, please include the below info in the header row. Designator, Mid X, Mid Y, Layer, Rotation.`

Best regards
ArchGalileu

**Comment by stuartpittaway** [comment]
Hello KICAD doesn't output CPL files, but it will produce a position file which should be similar.

I've uploaded it to here....

https://github.com/stuartpittaway/diyBMSv4/blob/master/Circuit/gerber/v4-top-pos.csv

**Comment by atanisoft** [comment]
@stuartpittaway take a look at https://github.com/matthewlai/JLCKicadTools/tree/master/jlc_lib which can generate the CPL and BOM file for JLC.

**Comment by ArchGalileu** [comment]
Will try ;)

Best regards 
ArchGalileu
