### ISSUE TITLE
Made new PCB with 14s on it

### ISSUE THREAD

**Issue by N1c084** [stuartpittaway/diyBMSv4#123]
Hi 
What do you think about to made one bank PCB (14s ) with only one tx/rx cable and link between each -/+ directly on PCB, like this we need less space and wires ?
See pic with only 2s for now 
![image](https://user-images.githubusercontent.com/101097267/185747756-f6c88336-b807-4288-8154-1e58031890a7.jpeg)

**Comment by N1c084** [comment]
Green wires are old design connexion for middle point.
Normally it would work nice without these 2 wires until it is a middle point the white is sufficient  .

**Comment by stuartpittaway** [comment]
As long as you don't share the power wires between the modules it should be ok.

**Comment by N1c084** [comment]
You mean voltage drop in wire when balancing will cause false reading to next cell on same wire?

>> for 1 meter wire 1mm²
R=0.0175ohm 
U=23mV for 1.3A ; ok i never think this value will be so high for so small wire/current

**Comment by stuartpittaway** [comment]
Correct.

**Comment by N1c084** [comment]
so i need to remove the link on PCB too, because it will cause current sharing in both wires
