### ISSUE TITLE
Component placement issue from JLCPCB

### ISSUE THREAD

**Issue by drawlusyk** [stuartpittaway/diyBMSv4#130]
Hello, I placed an order with JLCPCB for boards and component placement. 

Please see the included images which were provided in my order which they fixed.
![Produce_DanZhi SMT_Snapshot Top 2517233A_Y16 SMT02211271040507](https://user-images.githubusercontent.com/5085153/207237687-a8df3da7-3b29-4b93-b089-5b984d90a42c.png)
![Produce_DanZhi SMT_Original_Snapshot Top 2517233A_Y16 SMT02211271040507](https://user-images.githubusercontent.com/5085153/207237701-4880fcc7-416b-45ee-ba98-ec81bd5f9f52.png)
![Produce_DanZhi SMT_Original_Snapshot Top 2517233A_P2 SMT02211271040510](https://user-images.githubusercontent.com/5085153/207237705-ab76127a-b97c-4dbc-9545-c1b4a329dbd4.png)
![Produce_DanZhi SMT_Snapshot Top 2517233A_P2 SMT02211271040510](https://user-images.githubusercontent.com/5085153/207237711-411aa410-36f3-424c-b799-e8d7d02e71e9.png)

Also, the following email content was sent after my order...

****************
Please kindly note for The Standard PCBA, if the original design has no edge rail, we will add 5mm width edge rail on 2 sides of board. So the board size will increase which will lead to price changes.

Since the difference is small, we will not charge the extra fee for you this time, please kindly pay attention about this for the future orders.
***********

**Comment by stuartpittaway** [comment]
Just to add I've noticed they have INCORRECTLY rotated part D2 (diode) on the modules.  If you have already confirmed the order with JLC - DO NOT POWER ON THESE MODULES until you remove and rotate all the D2 diodes.

The + should be on the right, next to the "K" mark.

**Comment by drawlusyk** [comment]
Ok. I had to place an order for the missing part ATTINY841-SSU. At the same time of placing this order, I also ordered the pcb's. They thankfully sent an email letting me know that the parts will take a few days to arrive, so they cancelled the PCB order for me. Once parts are in, I will re-order with the updates. Thanks.

**Comment by stuartpittaway** [comment]
Right - the new modules won't be using the TINY841 :-)

**Comment by drawlusyk** [comment]
Huh? Did I upload the wrong files? I had to order 50 of these at $2 each since they didn't have them in stock.
Before ordering i did a git pull on the dir i have diybms files in. 
This is what i uploaded... diyBMSv4/ModuleV440/export/ModuleV440_bom_jlc.csv

Or are you changing components for v4.5?

**Comment by stuartpittaway** [comment]
Yes, changing components - the TINY841 is difficult to get hold of, often out of stock.

**Comment by stuartpittaway** [comment]
I've just uploaded the v4.5 files, feel free to use those if you want - but they need ATTINY1624 chip.

**Comment by drawlusyk** [comment]
Thanks Stuart. Will upload these to JLCPCB and let you know if there are any problems.

**Comment by drawlusyk** [comment]
JLCPCB is replacing the ATTINY1624-SSU-ND with is ATTINY1624-XF. Is this ok?
Still need to pre-order these but cheaper;)

**Comment by N1c084** [comment]
Not the same pitch, you need to change from soic to tssop

**Comment by stuartpittaway** [comment]
Did you see the video I just released? Shows the difference between the two.

You could always add the attiny chip on yourself (manually solder). Not difficult and likely lower cost than jlcpcb
