### ISSUE TITLE
Change Ina228 to ina229

### ISSUE THREAD

**Issue by Michi202020** [stuartpittaway/diyBMSv4#132]
Hello Stuart,

I found in Texas instruments the Ina229 and I have buy 30pcs.
I see that the code is the same but it's only the different i2c to SPI. Can you help me for the software that you can change the connection.
The Hardware I can change it self.
I thinks this part is easyer for a alternativ for the 228.

Many Thanks and Best Regards
Michel
![Screenshot_20221214_101752_com android email](https://user-images.githubusercontent.com/81771598/207556883-f6c08ab2-dd60-46d4-9a77-f035f2d557a6.jpg)

**Comment by Michi202020** [comment]
Hello,

if its possible that one person can me help withe the code to change the i2c to spi?
The code for the Ina229 is the same as Ina228 only the communication is the different.

Many Thanks and best Regards
Michael

**Comment by stuartpittaway** [comment]
Hi @Michi202020, I'm going to start work on this very soon.
Stu.

**Comment by Michi202020** [comment]
Hello Stuart,

Many thanks and we can write if you are starting withe this project.

Best Regards
Michael

**Comment by stuartpittaway** [comment]
The changes for the ina229 have now been released, check out my YouTube video for information.

**Comment by Michi202020** [comment]
Hello Stuart, many thanks for your work. I will check this in the next days.
Best Regards
Michael
