### ISSUE TITLE
Wrong C1 part number on new Modulev450

### ISSUE THREAD

**Issue by benjolsen** [stuartpittaway/diyBMSv4#136]
I am working through some issues getting the new module created on JLCPCB.  The part number for C1 comes up as a 0402 footprint.  I have looked up a similar spec'ed part that is in the 0805 footprint: C913936

Just wanted to let you know.

Thanks for all your great work!

 https://www.lcsc.com/product-detail/Multilayer-Ceramic-Capacitors-MLCC-SMD-SMT_Samsung-Electro-Mechanics-CL21B104KBCNNNL_C913936.html

**Comment by stuartpittaway** [comment]
Thanks for the heads up, this is now fixed - also raised as #138
