### ISSUE TITLE
ModuleV450 D2 polarity confusing

### ISSUE THREAD

**Issue by benjolsen** [stuartpittaway/diyBMSv4#137]
D2 has silkscreened around it:  K, +, and stripe.  JLCPCB is confused because the stripe indicates -, but the silkscreen says +.  I don't know what the K stands for :( .

I think the stripe is correct and the + is wrong.  Am I correct?

**Comment by stuartpittaway** [comment]
Hello @benjolsen ,

This is the data sheet for the part.
https://datasheet.lcsc.com/szlcsc/1912111437_AnBon-SMBJ5-0A_C440263.pdf

The part is a TVS UNIDIRECTIONAL DIODE - not a "standard" diode which I think is confusing JLC.

It should be installed similar to this circuit diagram.
![image](https://user-images.githubusercontent.com/1201909/208858278-10306858-b469-41a0-b273-50c89442a52d.png)

This is the marking on the device
![image](https://user-images.githubusercontent.com/1201909/208858392-3f1742e2-da72-4655-a704-ef97f102b09e.png)


Therefore pin 1 (with the STRIPE) needs to be fitted towards the POSITIVE incoming power - so the silkscreen with "STRIPE" and "+" is correct.

The part pin 1 needs to be aligned facing to the right


"K" indicates the cathode - which is also "positive"
