### ISSUE TITLE
Export temperature data of external sensor with one decimal to mqqt and influxdb

### ISSUE THREAD

**Issue by wurstyboy** [stuartpittaway/diyBMSv4#14]
In order to track your cells/packs it would be nice to get one decimals for the external probe temperature.

I guess changes are needed in Main.cpp (but I am actually a noob with programming...)
Line 518
     poststring = poststring + ",exttemp=" + String(cmi[bank][i].externalTemp)+"i";
and
Line 644-647
      if (cmi[bank][i].externalTemp!=-40) {
        sprintf(buffer, "diybms/%d/%d/exttemp", bank,i);
        sprintf(value, "%d", cmi[bank][i].externalTemp);
        mqttClient.publish(buffer, 0, true, value);

Maybe also in packet_processor.cpp of the cell modules...

**Comment by stuartpittaway** [comment]
Okay, the latest commit includes the external temperature publising over influxdb.  For modules without a sensor attached they will read -40 degrees C

MQTT already publishes this information.

I won't be adding in decimal points as this will require a complete change to the packet structure of the modules.
