### ISSUE TITLE
CPL file of ControllerCircuit 4.5 is diplacing the parts

### ISSUE THREAD

**Issue by olterion** [stuartpittaway/diyBMSv4#143]
Hello,

the CPL file in 
https://github.com/stuartpittaway/diyBMSv4/blob/master/ControllerCircuit/export/ControllerCircuit_cpl_jlc.csv 
has a offset to top left, if I import it in JLCPCB.

So, the parts are not placing on the PCB.

Please can you fix it?

Best regards,
Olli
![diybms_controller](https://user-images.githubusercontent.com/12214453/214277697-58593b7f-e98d-41d5-a8cc-5fd9f9dcfdec.PNG)

**Comment by stuartpittaway** [comment]
Click the "A" align button in JLCPCB website !
