### ISSUE TITLE
a question regarding the wiki

### ISSUE THREAD

**Issue by moscito1010** [stuartpittaway/diyBMSv4#144]
Hi Stuart
You describe the node red flow in the wiki and show a picture of it. Can I also download the flow somewhere?

**Comment by stuartpittaway** [comment]
Hello @moscito1010 , I don't have a wiki or use node red!

Was this published by a DIYBMS user?

**Comment by moscito1010** [comment]
from here
https://github.com/stuartpittaway/diyBMSv4/wiki/Visualize-data-from-the-diyBMS

**Comment by stuartpittaway** [comment]
Ah I see - thats user generated content by "donnib" - I don't use NodeRed.

Stu.

**Comment by stienman** [comment]
The nodered flow is in the article, hidden in a disclosure labeled
"►Details", immediately above the diagram.  Click "► Details" and it'll
show you the flow code, which I'll include below for convenience.

[
    {
        "id": "d737058.bd3b5f8",
        "type": "comment",
        "z": "efe93325.55893",
        "name": "Push cell data from MQTT to InfluxDB",
        "info": "",
        "x": 300,
        "y": 270,
        "wires": []
    },
    {
        "id": "4146fd37.aa7214",
        "type": "comment",
        "z": "efe93325.55893",
        "name": "Push diyBMS status from MQTT to InfluxDB",
        "info": "",
        "x": 320,
        "y": 375,
        "wires": []
    },
    {
        "id": "bb75249b.baa748",
        "type": "comment",
        "z": "efe93325.55893",
        "name": "Push diyBMS relay status from MQTT to InfluxDB",
        "info": "",
        "x": 330,
        "y": 495,
        "wires": []
    },
    {
        "id": "d2e3da5e.46cb48",
        "type": "influxdb out",
        "z": "efe93325.55893",
        "influxdb": "a6fdab90.b072d8",
        "name": "",
        "measurement": "",
        "precision": "",
        "retentionPolicy": "",
        "database": "database",
        "precisionV18FluxV20": "ms",
        "retentionPolicyV18Flux": "",
        "org": "home",
        "bucket": "diybms",
        "x": 910,
        "y": 675,
        "wires": []
    },
    {
        "id": "5f31136b.6f802c",
        "type": "comment",
        "z": "efe93325.55893",
        "name": "Push diyBMS rules status from MQTT to InfluxDB",
        "info": "",
        "x": 330,
        "y": 765,
        "wires": []
    },
    {
        "id": "60dc208.35703e",
        "type": "change",
        "z": "efe93325.55893",
        "name": "relay2",
        "rules": [
            {
                "t": "set",
                "p": "measurement",
                "pt": "msg",
                "to": "relays",
                "tot": "str"
            },
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "[\t   {\t       \"state\":payload.\"1\"\t   },\t
{\t       \"relay\":\"2\"\t   }\t]",
                "tot": "jsonata"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 500,
        "y": 585,
        "wires": [
            [
                "d2e3da5e.46cb48"
            ]
        ]
    },
    {
        "id": "a5494dd2.bb4c1",
        "type": "change",
        "z": "efe93325.55893",
        "name": "relay3",
        "rules": [
            {
                "t": "set",
                "p": "measurement",
                "pt": "msg",
                "to": "relays",
                "tot": "str"
            },
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "[\t   {\t       \"state\":payload.\"2\"\t   },\t
{\t       \"relay\":\"3\"\t   }\t]",
                "tot": "jsonata"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 500,
        "y": 630,
        "wires": [
            [
                "d2e3da5e.46cb48"
            ]
        ]
    },
    {
        "id": "c0aa04b9.bd0858",
        "type": "change",
        "z": "efe93325.55893",
        "name": "relay4",
        "rules": [
            {
                "t": "set",
                "p": "measurement",
                "pt": "msg",
                "to": "relays",
                "tot": "str"
            },
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "[\t   {\t       \"state\":payload.\"3\"\t   },\t
{\t       \"relay\":\"4\"\t   }\t]",
                "tot": "jsonata"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 500,
        "y": 675,
        "wires": [
            [
                "d2e3da5e.46cb48"
            ]
        ]
    },
    {
        "id": "11d99b54.441385",
        "type": "mqtt in",
        "z": "efe93325.55893",
        "name": "",
        "topic": "diybms/output",
        "qos": "2",
        "datatype": "json",
        "broker": "d77c97be.ca8e08",
        "x": 230,
        "y": 600,
        "wires": [
            [
                "4b948575.b5c37c",
                "60dc208.35703e",
                "a5494dd2.bb4c1",
                "c0aa04b9.bd0858"
            ]
        ]
    },
    {
        "id": "4b948575.b5c37c",
        "type": "change",
        "z": "efe93325.55893",
        "name": "relay1",
        "rules": [
            {
                "t": "set",
                "p": "measurement",
                "pt": "msg",
                "to": "relays",
                "tot": "str"
            },
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "[\t   {\t       \"state\":payload.\"0\"\t   },\t
{\t       \"relay\":\"1\"\t   }\t]",
                "tot": "jsonata"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 500,
        "y": 540,
        "wires": [
            [
                "d2e3da5e.46cb48"
            ]
        ]
    },
    {
        "id": "d860bb6e.6de468",
        "type": "change",
        "z": "efe93325.55893",
        "name": "",
        "rules": [
            {
                "t": "set",
                "p": "measurement",
                "pt": "msg",
                "to": "cells",
                "tot": "str"
            },
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "[\t   payload,\t   {\t
\"cell\":$substringAfter($.topic, 'diybms\\/0\\/')\t   }\t]",
                "tot": "jsonata"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 410,
        "y": 315,
        "wires": [
            [
                "d2e3da5e.46cb48"
            ]
        ]
    },
    {
        "id": "2d6c5e93.760ba2",
        "type": "change",
        "z": "efe93325.55893",
        "name": "",
        "rules": [
            {
                "t": "set",
                "p": "measurement",
                "pt": "msg",
                "to": "status",
                "tot": "str"
            },
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "{\t  \"uptime\": payload.uptime,\t  \"bankVoltage\":
payload.bankVoltage[0],\t  \"comserr\": payload.monitor.commserr,\t
 \"sent\": payload.monitor.sent,\t  \"received\" :
payload.monitor.received,\t  \"badcrc\" : payload.monitor.badcrc,\t
 \"ignored\" : payload.monitor.ignored,\t  \"oss\" : payload.monitor.oss,\t
 \"roundtrip\" : payload.monitor.roundtrip\t}",
                "tot": "jsonata"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 425,
        "y": 420,
        "wires": [
            [
                "d2e3da5e.46cb48"
            ]
        ]
    },
    {
        "id": "ca71e196.4e9b7",
        "type": "change",
        "z": "efe93325.55893",
        "name": "rule1",
        "rules": [
            {
                "t": "set",
                "p": "measurement",
                "pt": "msg",
                "to": "rules",
                "tot": "str"
            },
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "[\t   {\t       \"state\":payload.\"0\"\t   },\t
{\t       \"rule\":\"1\"\t   }\t]",
                "tot": "jsonata"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 500,
        "y": 825,
        "wires": [
            [
                "d2e3da5e.46cb48"
            ]
        ]
    },
    {
        "id": "172d8ecc.c116a1",
        "type": "mqtt in",
        "z": "efe93325.55893",
        "name": "",
        "topic": "diybms/0/#",
        "qos": "2",
        "datatype": "json",
        "broker": "d77c97be.ca8e08",
        "x": 220,
        "y": 315,
        "wires": [
            [
                "d860bb6e.6de468"
            ]
        ]
    },
    {
        "id": "830f3ce9.9c478",
        "type": "mqtt in",
        "z": "efe93325.55893",
        "name": "",
        "topic": "diybms/status",
        "qos": "2",
        "datatype": "json",
        "broker": "d77c97be.ca8e08",
        "x": 220,
        "y": 420,
        "wires": [
            [
                "2d6c5e93.760ba2"
            ]
        ]
    },
    {
        "id": "f55b4ea.29e3cb",
        "type": "mqtt in",
        "z": "efe93325.55893",
        "name": "",
        "topic": "diybms/rule",
        "qos": "2",
        "datatype": "json",
        "broker": "d77c97be.ca8e08",
        "x": 220,
        "y": 1020,
        "wires": [
            [
                "ca71e196.4e9b7",
                "213a9d0f.eed592",
                "7f6f74a1.b55a2c",
                "749c1cc2.344c24",
                "1eac9398.9a358c",
                "c6f226e4.30ae78",
                "f721fa6a.7c75a8",
                "2637ac1d.928b54",
                "299e0e34.9876b2",
                "2a7fca0e.25e1c6",
                "25f975c8.dce94a"
            ]
        ]
    },
    {
        "id": "213a9d0f.eed592",
        "type": "change",
        "z": "efe93325.55893",
        "name": "rule2",
        "rules": [
            {
                "t": "set",
                "p": "measurement",
                "pt": "msg",
                "to": "rules",
                "tot": "str"
            },
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "[\t   {\t       \"state\":payload.\"0\"\t   },\t
{\t       \"rule\":\"2\"\t   }\t]",
                "tot": "jsonata"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 500,
        "y": 870,
        "wires": [
            [
                "d2e3da5e.46cb48"
            ]
        ]
    },
    {
        "id": "7f6f74a1.b55a2c",
        "type": "change",
        "z": "efe93325.55893",
        "name": "rule3",
        "rules": [
            {
                "t": "set",
                "p": "measurement",
                "pt": "msg",
                "to": "rules",
                "tot": "str"
            },
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "[\t   {\t       \"state\":payload.\"0\"\t   },\t
{\t       \"rule\":\"3\"\t   }\t]",
                "tot": "jsonata"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 500,
        "y": 915,
        "wires": [
            [
                "d2e3da5e.46cb48"
            ]
        ]
    },
    {
        "id": "749c1cc2.344c24",
        "type": "change",
        "z": "efe93325.55893",
        "name": "rule4",
        "rules": [
            {
                "t": "set",
                "p": "measurement",
                "pt": "msg",
                "to": "rules",
                "tot": "str"
            },
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "[\t   {\t       \"state\":payload.\"0\"\t   },\t
{\t       \"rule\":\"4\"\t   }\t]",
                "tot": "jsonata"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 500,
        "y": 960,
        "wires": [
            [
                "d2e3da5e.46cb48"
            ]
        ]
    },
    {
        "id": "1eac9398.9a358c",
        "type": "change",
        "z": "efe93325.55893",
        "name": "rule5",
        "rules": [
            {
                "t": "set",
                "p": "measurement",
                "pt": "msg",
                "to": "rules",
                "tot": "str"
            },
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "[\t   {\t       \"state\":payload.\"0\"\t   },\t
{\t       \"rule\":\"5\"\t   }\t]",
                "tot": "jsonata"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 500,
        "y": 1005,
        "wires": [
            [
                "d2e3da5e.46cb48"
            ]
        ]
    },
    {
        "id": "c6f226e4.30ae78",
        "type": "change",
        "z": "efe93325.55893",
        "name": "rule6",
        "rules": [
            {
                "t": "set",
                "p": "measurement",
                "pt": "msg",
                "to": "rules",
                "tot": "str"
            },
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "[\t   {\t       \"state\":payload.\"0\"\t   },\t
{\t       \"rule\":\"6\"\t   }\t]",
                "tot": "jsonata"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 500,
        "y": 1050,
        "wires": [
            [
                "d2e3da5e.46cb48"
            ]
        ]
    },
    {
        "id": "f721fa6a.7c75a8",
        "type": "change",
        "z": "efe93325.55893",
        "name": "rule7",
        "rules": [
            {
                "t": "set",
                "p": "measurement",
                "pt": "msg",
                "to": "rules",
                "tot": "str"
            },
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "[\t   {\t       \"state\":payload.\"0\"\t   },\t
{\t       \"rule\":\"7\"\t   }\t]",
                "tot": "jsonata"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 500,
        "y": 1095,
        "wires": [
            [
                "d2e3da5e.46cb48"
            ]
        ]
    },
    {
        "id": "2637ac1d.928b54",
        "type": "change",
        "z": "efe93325.55893",
        "name": "rule8",
        "rules": [
            {
                "t": "set",
                "p": "measurement",
                "pt": "msg",
                "to": "rules",
                "tot": "str"
            },
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "[\t   {\t       \"state\":payload.\"0\"\t   },\t
{\t       \"rule\":\"8\"\t   }\t]",
                "tot": "jsonata"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 500,
        "y": 1140,
        "wires": [
            [
                "d2e3da5e.46cb48"
            ]
        ]
    },
    {
        "id": "299e0e34.9876b2",
        "type": "change",
        "z": "efe93325.55893",
        "name": "rule9",
        "rules": [
            {
                "t": "set",
                "p": "measurement",
                "pt": "msg",
                "to": "rules",
                "tot": "str"
            },
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "[\t   {\t       \"state\":payload.\"0\"\t   },\t
{\t       \"rule\":\"9\"\t   }\t]",
                "tot": "jsonata"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 500,
        "y": 1185,
        "wires": [
            [
                "d2e3da5e.46cb48"
            ]
        ]
    },
    {
        "id": "2a7fca0e.25e1c6",
        "type": "change",
        "z": "efe93325.55893",
        "name": "rule10",
        "rules": [
            {
                "t": "set",
                "p": "measurement",
                "pt": "msg",
                "to": "rules",
                "tot": "str"
            },
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "[\t   {\t       \"state\":payload.\"0\"\t   },\t
{\t       \"rule\":\"10\"\t   }\t]",
                "tot": "jsonata"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 500,
        "y": 1230,
        "wires": [
            [
                "d2e3da5e.46cb48"
            ]
        ]
    },
    {
        "id": "25f975c8.dce94a",
        "type": "change",
        "z": "efe93325.55893",
        "name": "rule11",
        "rules": [
            {
                "t": "set",
                "p": "measurement",
                "pt": "msg",
                "to": "rules",
                "tot": "str"
            },
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "[\t   {\t       \"state\":payload.\"0\"\t   },\t
{\t       \"rule\":\"11\"\t   }\t]",
                "tot": "jsonata"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 500,
        "y": 1275,
        "wires": [
            [
                "d2e3da5e.46cb48"
            ]
        ]
    },
    {
        "id": "a6fdab90.b072d8",
        "type": "influxdb",
        "hostname": "127.0.0.1",
        "port": "8086",
        "protocol": "http",
        "database": "database",
        "name": "Influx",
        "usetls": false,
        "tls": "",
        "influxdbVersion": "2.0",
        "url": "http://influxdb:8086",
        "rejectUnauthorized": true
    },
    {
        "id": "d77c97be.ca8e08",
        "type": "mqtt-broker",
        "name": "Mosquitto",
        "broker": "10.10.0.9",
        "port": "1883",
        "clientid": "",
        "usetls": false,
        "compatmode": false,
        "keepalive": "60",
        "cleansession": true,
        "birthTopic": "",
        "birthQos": "0",
        "birthPayload": "",
        "closeTopic": "",
        "closeQos": "0",
        "closePayload": "",
        "willTopic": "",
        "willQos": "0",
        "willPayload": ""
    }
]
