### ISSUE TITLE
New ESP32_Devkitc_V4 ESP32-WROOM-DA GPIO2 pin not led out to the module.

### ISSUE THREAD

**Issue by cor-mt** [stuartpittaway/diyBMSv4#147]
I have a DIYBMS CONTROLLER V4.2 from 9 May 2021 that I'm trying to get working with 8 v4.4 modules.

The first problem I ran into was a dead short to ground on my ESP-WROOM-32D's GPIO2 pin. Al the local suppliers are out of stock on them, the only model available is the "ESP-WROOM-DA" where GPIO2 and GPIO25 are used for antenna selection and not led out to the module. (P10 in data sheet)

Is there a mod that can be done to map and wire the module RX to a different pin and get the comms going? Like a mod wire between GPIO2 and GPIO35, but what code need to change? The "DA" version seem to be the new goto version, maybe future compatibility and for now a warning that it is not compatible although an ESP32_Devkitc module in the readme?

**Comment by stuartpittaway** [comment]
As you mention the DIYBMS uses the DEVKIT-C module footprint/pinout.

It would be quite a change to incorporate a move to the DA version - including both hardware and software changes.

Potentially there may no longer be enough GPIO pins for running everything on the board.
