### ISSUE TITLE
Part codes for C1 is an 0402 package and should be 0805

### ISSUE THREAD

**Issue by stuartpittaway** [stuartpittaway/diyBMSv4#150]
**ModuleV450-bom.csv**
**ModuleV450_bom_jlc.csv**

Part codes for C1 is an 0402 package and should be 0805

I've gone with the following replacement part for my build: -

Samsung part: CL21B104KBCWPNC
LCSC part: C307361

_Originally posted by @safurniss in https://github.com/stuartpittaway/diyBMSv4/issues/149#issuecomment-1455967061_

**Comment by safurniss** [comment]
this is in the 4.6 branch. in the Master branch it shows part C49678
