### ISSUE TITLE
LTO Battery

### ISSUE THREAD

**Issue by Michi202020** [stuartpittaway/diyBMSv4#152]
Hello Stuart,

I have a LTO Battery in 20s1p. In your Video I hear from you that the Attiny 1624 works down to 1,8volt. My LTO works from 1,9 to 2,9volts. If it's not to down with the voltage 1,9 to 1,8 volts?
Have you a time line how do you start withe the LTO configuration?

Best Regards
Michael

**Comment by stuartpittaway** [comment]
Hi Michael, I've not really looked at really low voltage cells like the LTO.

Operating at 1.8V is difficult as a lot of components are not suitable at such low voltages.
