### ISSUE TITLE
JLCPCB - Ask For Clarification: Polarization of D2, D3 and D4

### ISSUE THREAD

**Issue by addame** [stuartpittaway/diyBMSv4#154]
Hi @stuartpittaway,

JLCPCB is asking to confirm the polarity of D2, D3 and D4 (see bellow the polarities JLCPCB wants to be confirmed). 
For D2 and D3, I have seen that an answer is already given (issue #146): 

- The CATHODE (-) of D2 pointing to the RIGHT of the PCB. Is it correct? 
- The CATHODE (-) of D3 pointing to the LEFT of the PCB. Is it correct?

Is the CATHODE (-) of D4 also pointing to the LEFT of the PCB?

Thank you!

![image](https://user-images.githubusercontent.com/37374/233426394-8c72acee-cdeb-4ed2-b9df-6e04538187bc.png)

**Comment by floreseken** [comment]
They asked me the same thing, but only about D2. I asked them to reverse D2, to match the plus with the plus.

But that was the wrong decision, got the boards with D2 in the wrong direction.

Luckily this this the easiest part to desolder and reverse...

**Comment by stuartpittaway** [comment]
@addame as @floreseken pointed out, the rotation should be correct as you have it in the picture.

JLC can't seem to get their head around D2 being a TVS diode - or their stock system is setup incorrectly.

**Comment by addame** [comment]
@floreseken and @stuartpittaway thank you for the clarification!
