### ISSUE TITLE
Can the v4.5 modules work with the ESP8266 controller?

### ISSUE THREAD

**Issue by floreseken** [stuartpittaway/diyBMSv4#158]
Can the v4.5 modules work with the ESP8266 controller?

I made this combination because of the simplicity of the old controller.

I flashed the controllers and the modules with the latest pre-compiled HEX files I could find in the releases.
But my setup does not work now, and I think I know why..

The controller uses 2400 baud comms by default and the modules 5000 or 10000 baud. Right?

But this got me wondering, is this setup even possible? Can I get this to work with a controller firmware at 5000 baud or do I need the new controller? (Or run the modules at 2400?)

Thanks..

**Comment by stuartpittaway** [comment]
I added a 2K4 version of the 4.5 code (slower baud rate) to the last release, see if that one works with the old style controller.

**Comment by floreseken** [comment]
I totally overlooked the 2K4 version for the1624, dumb of me..

**Comment by stuartpittaway** [comment]
If you have it running reliably at 5000 baud, then stay at that speed, if you find you have communication issues then drop down to the 2400.
