### ISSUE TITLE
v450 module BOM incorrectly has JLCPCB part number for ATTINY1624-XF not ATTINY1624-SSU-ND

### ISSUE THREAD

**Issue by moscito1010** [stuartpittaway/diyBMSv4#159]
Hello Stuart. I had the 450 modules made and ordered the attiny1624, which is displayed in the parts list (Matched Part Details) at JLCPCB as 1624-XF. I would have to order the Attinys from another source because JLCPCB doesn't have enough of them anymore.
But that is wrong, it must be the 1624SSU. The XF version has a different design.

Stupid if you rely on the "Matched part details" and order a lot of unusable IC's.
Please change that as soon as possible. A few friends have the exact same problem independently of me. Altogether we now have over 150 ICs that we cannot use and probably cannot be exchanged.
Annoying, really very annoying.

**Comment by moscito1010** [comment]
![attiny1624](https://github.com/stuartpittaway/diyBMSv4/assets/75945899/064d108f-0a0c-4c24-ab13-8975a9c00691)

**Comment by floreseken** [comment]
I guess this is something that JCL does, because in the BOM here https://github.com/stuartpittaway/diyBMSv4/blob/master/ModuleV450/export/ModuleV450_bom_jlc.csv is seems correct to me..

**Comment by atanisoft** [comment]
@stuartpittaway The BOM references the incorrect part id, it should be C5160891.

**Comment by stuartpittaway** [comment]
Just reviewing this, the BOM has the correct part name, and footprint, but different JLC/LCSC reference as @atanisoft mentions.

https://github.com/stuartpittaway/diyBMSv4/blob/fd6a1215384bf0d6ed1b0e1400e637dcbcc31cc9/ModuleV450/export/ModuleV450-bom.csv?plain=1#L22

I shall update the BOM to correct the part number.

**Comment by stuartpittaway** [comment]
After update, BOM is now correctly showing part code C5160891

https://github.com/stuartpittaway/diyBMSv4/blob/c647f4783f0446b8902fa3d2e6b6e2dbf678e7ff/ModuleV450/export/ModuleV450-bom.csv?plain=1#L22
