### ISSUE TITLE
Error Relay Active balancer activation

### ISSUE THREAD

**Issue by chapulino** [stuartpittaway/diyBMSv4#165]
Stuart, with this configuration and the current voltages, the relay that activates the active balancer should activate, close the circuit and activate that balancer, but it does not, I am configuring something wrong. Could it be a hardware problem?
I have tried it in two different All in One

![image](https://github.com/stuartpittaway/diyBMSv4/assets/14351899/72478315-74e4-4d16-b16d-69fa543edf73)

**Comment by stuartpittaway** [comment]
Have you tried the latest code?  https://github.com/stuartpittaway/diyBMSv4ESP32/actions/runs/5831005455

**Comment by chapulino** [comment]
Not , i use the 8/08/2023 version . I'm going to try it

**Comment by chapulino** [comment]
ok solved, thanks
