### ISSUE TITLE
Fuse F1 on All-in-one board is not rated to 65V

### ISSUE THREAD

**Issue by Roelaynd** [stuartpittaway/diyBMSv4#172]
Suggest to use fuse:
Bourns CMF-RL55A-0

https://nl.mouser.com/datasheet/2/54/cmfrl-777106.pdf

**Comment by stuartpittaway** [comment]
Thanks for reporting this.

The existing part number is JK250-100U - however on LCSC there are a number of parts with the same number but different specs!

The correct LCSC stock code is C2680606 - ShenZhen JinRui Electronic Material Co.,Ltd
https://www.lcsc.com/product-detail/Resettable-Fuses_Jinrui-Electronic-Materials-Co-JK250-100U_C2680606.html

Which is a 250V fuse.


I've updated the BOM.
