### ISSUE TITLE
Module V490 AIO CPL file is missing all the "J" parts

### ISSUE THREAD

**Issue by JasonMBarnard** [stuartpittaway/diyBMSv4#184]
I tried ordering a V490 AIO from JLCPCB and uploaded all the files per the instructions.  I received an alert that the CPL file was missing all the placement information for several parts.  Most appeared to be all the parts starting with "J".  Sure enough when I opened the CPL CSV file none of the "J" parts are listed in the file.  I got the impression JLCPCB had the parts but could not place them on the board without this information.

**Comment by stuartpittaway** [comment]
Kicad doesn't output the manual soldered part locations automatically.  If you are only making a few boards, I'd recommend buying those parts from lcsc and manually soldering them on to save money.

Jlcpcb generally don't have stock of the voltage reference chip either!
