### ISSUE TITLE
BOM: out of stock 450k resistor

### ISSUE THREAD

**Issue by maglub** [stuartpittaway/diyBMSv4#2]
Hi,

The following product is currently out of stock.

https://lcsc.com/product-detail/_RC0805FR-07475KL_C137521.html

What would be a suitable replacement?

**Comment by maglub** [comment]
This one seems to be available instead:

https://lcsc.com/product-detail/Others_Huaxin-S-T-WR08X4753FTL_C334915.html

**Comment by stuartpittaway** [comment]
Yes looks like it would work.  Any resistor with these specifications should be okay

Chip Resistor - Surface Mount 475KOhms ±1% 1/8W 0805 RoHS

Its the +/- 1% thats important
