### ISSUE TITLE
Display

### ISSUE THREAD

**Issue by gen-ben** [stuartpittaway/diyBMSv4#24]
In order to monitor cells voltage and temperature it would be nice to have small display shows total battery voltage, max cell temperature and min&max cell voltage.
I am planing to connect a TFT display to ESP8266 using TXD0 and RXD0 pins, but my knowledge with programming is very limited can you show me where should I make changes to export those values via serial port
thanks

**Comment by stuartpittaway** [comment]
Hello, you should be able to connect a display to the existing ESP controller (you don't need a second one) using the i2c connections on the controller board.  I've not looked into it myself but should be easy enough.

**Comment by gen-ben** [comment]
hello, thanks for your reply, yes i will use the existing ESP but I meant that could I use the free Serial port with TX and RX labels on wemos board to communicate with TFT display or other microcontroller?.
you are using Serial and Serial1 in your code is there any way to add another serial function to control the third one.

![d1-mini-esp8266-board-sh_fixled](https://user-images.githubusercontent.com/56996510/75615140-45d09e80-5b51-11ea-986d-aeed2988295b.jpg)
