### ISSUE TITLE
Controller Schematic

### ISSUE THREAD

**Issue by SirGioVan** [stuartpittaway/diyBMSv4#25]
I try use KiCAD to can see the controller board ,  but is complicated for new users , is possible share PDF schematic ? 
![Missing Schematic](https://user-images.githubusercontent.com/16431665/73048919-93aa0680-3e2f-11ea-980d-e022ea2a0281.JPG)

**Comment by stuartpittaway** [comment]
I've just uploaded a PDF version into GITHUB for you.

**Comment by SirGioVan** [comment]
Thanks a lot Stuart , i realy aprreciate your work , i hope very soon make some contibution
