### ISSUE TITLE
Internal temperature reading problem (when splitting packs in multiple banks)

### ISSUE THREAD

**Issue by Klauzen** [stuartpittaway/diyBMSv4#26]
I've also a problem to report, by splitting the packs in to banks (bank0 and bank1).

The internal temperature on bank0 is updating permanent perfectly, while the bank1 is not updating the temperature. When I restart the controller, the current temperatures of both banks are listed correct on the webpage. Afterwards, only the bank0 is updating!

**Comment by stuartpittaway** [comment]
Thanks for reporting, I'll try and take a look over the weekend.

**Comment by mkranjcic** [comment]
This is same problem that I have with 20 modules. My conclusion is that queue is overfilled with messages, and messages for bank1 are skipped while for bank0 fit into queue.
It seams like generating messages and putting into queue is faster than emptying queue. 
It has helped when timer for generating messages was increased to 12s - for my setup.

**Comment by Klauzen** [comment]
Ah okay! Maybe this also help for investigating the problem: Since I updated the code to the newest version of every cell and the controller board (I didn't updated since november 2019), the green LED's doesn't blink trough in one passing. Much more, bank0 is blinking trough 2...4 times and after a short break the bank1 is following with only one cycle... then, it repeats.

**Comment by stuartpittaway** [comment]
Hi, I've updated the controller code to add some debug timings so we can diagnose this problem better.

You will need to connect a serial terminal to the 2 debug pins on the controller, the serial output will now include a "T" and "E" value.  The T is an indication of the milliseconds taken between the request going out and the reply being received.  The E is an internal counter, which could indicate queue jams.

`S:80/1/23=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =87BC/Q:3 #  T:470 E:0 R:82/81/23=F02 F02 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =476B
`

The above example is 470ms which is 4 modules configured in 2 banks, although 4 modules in 1 bank produces about the same timing.

Thats about 117ms for each module to process the packet and transmit the data.  20 modules should take 2340milliseconds - or about 2.5 seconds per request to pass through all 20 modules.

For 2 banks, we make a request every 4 seconds which then queues 4 messages (timerEnqueueCallback)

Every half second, we test for replies (timerTransmitCallback) an error is generated if we have not received a reply after 20 calls to this routine (about 10 seconds)






Note that the code has now moved to its own repo
https://github.com/stuartpittaway/diyBMSv4Code

**Comment by Klauzen** [comment]
Hey Stuart,
thanks! After building and uploading the required code to the ESP, here is the console output:
`Found pcf8574
Clear AP settings1
Setup Access Point
mode : sta(84:f3:eb:e4:6f:03)
add if0
scandone
del if0
usl
mode : softAP(86:f3:eb:e4:6f:03)
add if1
dhcp server start:(ip:192.168.4.1,mask:255.255.255.0,gw:192.168.4.1)
bcn 100
S:80/1/1=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =925/Q:2 # Rules:000000100=
 T:1411 E:2 R:87/81/1=FE6 FE2 FEB FE6 FE6 FE2 FE6 0 0 0 0 0 0 0 0 0  =B891
S:80/3/2=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =7301/Q:1 #  T:1410 E:2 R:87/83/2=3332 3332 3332 3332 3332 3332 3331 0 0 0 0 0 0 0 0 0  =47CB
S:80/4/3=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =CA8E/Q:0 #  T:1399 E:2 R:87/84/3=0 0 2 0 0 0 2 0 0 0 0 0 0 0 0 0  =AAB7
S:80/1/4=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =C5D6/Q:1 #  T:1405 E:2 R:87/81/4=FE6 FE2 FE6 FE6 FE6 FE2 FE6 0 0 0 0 0 0 0 0 0  =F627
Rules:000001000=
S:80/3/5=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =9799/Q:0 #  T:1410 E:2 R:87/83/5=3332 3332 3332 3332 3332 3332 3331 0 0 0 0 0 0 0 0 0  =A353
S:80/1/6=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =EDBD/Q:1 #  T:1404 E:2 R:87/81/6=FE6 FE2 FEB FE6 FE6 FE2 FE6 0 0 0 0 0 0 0 0 0  =5C09
S:80/3/7=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =BFF2/Q:0 #  T:1410 E:2 R:87/83/7=3332 3332 3332 3332 3332 3332 3331 0 0 0 0 0 0 0 0 0  =8B38
Rules:000001000=
S:80/1/8=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =34AC/Q:1 #  T:1404 E:2 R:87/81/8=FE6 FE2 FEB FE6 FE6 FE2 FE6 0 0 0 0 0 0 0 0 0  =8518
S:80/3/9=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =66E3/Q:0 #  T:1410 E:2 R:87/83/9=3332 3332 3332 3332 3432 3332 3331 0 0 0 0 0 0 0 0 0  =7939
Rules:000001000=
S:80/1/A=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =1CC7/Q:1 #  T:1405 E:2 R:87/81/A=FEB FE2 FEB FE6 FE6 FE2 FEB 0 0 0 0 0 0 0 0 0  =35B8
S:80/3/B=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =4E88/Q:0 #  T:1410 E:2 R:87/83/B=3332 3332 3332 3332 3432 3332 3331 0 0 0 0 0 0 0 0 0  =5152
S:80/1/C=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =647A/Q:1 # Rules:000001000=
 T:1404 E:2 R:87/81/C=FE6 FE2 FEB FE6 FE6 FE2 FE6 0 0 0 0 0 0 0 0 0  =D5CE
S:80/3/D=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =3635/Q:0 #  T:1410 E:2 R:87/83/D=3332 3332 3432 3432 3432 3332 3332 0 0 0 0 0 0 0 0 0  =D525
S:80/1/E=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =4C11/Q:1 #  T:1404 E:2 R:87/81/E=FE6 FE2 FEB FE6 FE6 FE2 FE6 0 0 0 0 0 0 0 0 0  =FDA5
S:80/3/F=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =1E5E/Q:0 # Rules:000001000=
 T:1410 E:2 R:87/83/F=3332 3332 3432 3432 3432 3332 3332 0 0 0 0 0 0 0 0 0  =FD4E
S:80/1/10=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =C679/Q:1 #  T:1404 E:2 R:87/81/10=FE6 FE2 FEB FE6 FE6 FE2 FE6 0 0 0 0 0 0 0 0 0  =77CD
S:80/3/11=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =9436/Q:0 #  T:1410 E:2 R:87/83/11=3332 3332 3432 3432 3432 3332 3332 0 0 0 0 0 0 0 0 0  =7726
Rules:000001000=
S:80/1/12=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =EE12/Q:1 #  T:1404 E:2 R:87/81/12=FE6 FE2 FEB FE6 FE6 FE2 FE6 0 0 0 0 0 0 0 0 0  =5FA6
S:80/3/13=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =BC5D/Q:0 #  T:1410 E:2 R:87/83/13=3332 3332 3432 3432 3432 3332 3332 0 0 0 0 0 0 0 0 0  =5F4D
Rules:000001000=
S:80/1/14=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =96AF/Q:1 #  T:1405 E:2 R:87/81/14=FE6 FE2 FEB FE6 FE6 FE2 FE6 0 0 0 0 0 0 0 0 0  =271B
S:80/3/15=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =C4E0/Q:0 #  T:1410 E:2 R:87/83/15=3332 3332 3432 3432 3432 3332 3332 0 0 0 0 0 0 0 0 0  =27F0
S:80/1/16=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =BEC4/Q:1 # Rules:000001000=
 T:1404 E:2 R:87/81/16=FE6 FE2 FEB FE6 FE6 FE2 FE6 0 0 0 0 0 0 0 0 0  =F70
S:80/3/17=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =EC8B/Q:0 #  T:1410 E:2 R:87/83/17=3332 3432 3432 3432 3432 3332 3332 0 0 0 0 0 0 0 0 0  =FD6B
`
There are two thing, which confuses me:
- after installing the ESPControllerCode, only the first bank (bank0) is blinking through. The bank1 is not flashing...
- is it ok, if the ESP is not connected to the wifi (and the wifi-boot-webpage is shown), after flashing the esp?

Becouse the result is strange, here is the serial output of the normal ESPControler (from the inital issue)
`Found pcf8574
Connecting to WIFI
Connecting to Wi-Fi...
mode : sta(84:f3:eb:e4:6f:03)
add if0
scandone
state: 0 -> 2 (b0)
state: 2 -> 3 (0)
state: 3 -> 5 (10)
add 0
aid 2
cnt 

connected with LB2, channel 6
dhcp client start...
S:80/1/1=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =925/Q:5 # ip:192.168.8.101,mask:255.255.255.0,gw:192.168.8.1
Connected to Wi-Fi.
3. Connected IP:192.168.8.101
Requesting NTP from time.google.com
Got NTP time: 22:55:31 15/02/2020
Rules:000000111=Relay:0=0
Rules:010000111=
pm open,type:2 0
S:80/3/2=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =7301/Q:12 # Rules:010000111=
S:80/4/3=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =CA8E/Q:11 # S:90/1/4=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =7184/Q:10 # S:90/3/5=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =23CB/Q:13 # R:87/84/3=0 0 2 0 0 0 2 0 0 0 0 0 0 0 0 0  =AAB7**FAILED PROCESS REPLY**

S:90/4/6=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =B22F/Q:12 # R:97/81/4=FEB FD9 FE2 FEB FEB FEB FCC 0 0 0 0 0 0 0 0 0  =99FE**FAILED PROCESS REPLY**

S:80/1/7=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =7198/Q:11 # R:97/83/5=3432 3432 3432 3432 3432 3432 3432 0 0 0 0 0 0 0 0 0  =9B08**FAILED PROCESS REPLY**


S:80/3/8=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =FAC6/Q:10 # R:97/84/6=0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0  =31E1**FAILED PROCESS REPLY**

S:90/1/9=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =1CDB/Q:9 # R:87/81/7=FE6 FE2 FEB FE6 FE6 FE2 FE6 0 0 0 0 0 0 0 0 0  =C02C**FAILED PROCESS REPLY**

S:90/3/A=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =66FF/Q:8 # R:87/83/8=3432 3432 3432 3432 3432 3432 3432 0 0 0 0 0 0 0 0 0  =4205**FAILED PROCESS REPLY**

S:80/1/B=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =80E2/Q:7 # R:97/81/9=FEB FD9 FE2 FEB FEB FEB FD0 0 0 0 0 0 0 0 0 0  =F487**FAILED PROCESS REPLY**

S:80/3/C=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =AA10/Q:6 # R:97/83/A=3432 3432 3432 3432 3432 3432 3432 0 0 0 0 0 0 0 0 0  =DE3C**FAILED PROCESS REPLY**

Rules:010000111=
S:90/1/D=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =4C0D/Q:9 # R:87/81/B=FE6 FE2 FEB FE6 FE6 FE2 FE6 0 0 0 0 0 0 0 0 0  =3156**FAILED PROCESS REPLY**

S:90/3/E=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =3629/Q:8 # R:87/83/C=3432 3432 3432 3432 3432 3432 3432 0 0 0 0 0 0 0 0 0  =12D3**FAILED PROCESS REPLY**

S:80/1/F=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =D034/Q:7 # R:97/81/D=FEB FD9 FE2 FEB FEB FEB FD0 0 0 0 0 0 0 0 0 0  =A451**FAILED PROCESS REPLY**

S:80/3/10=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =813/Q:6 # R:97/83/E=3432 3432 3432 3432 3432 3432 3432 0 0 0 0 0 0 0 0 0  =8EEA**FAILED PROCESS REPLY**

S:90/1/11=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =EE0E/Q:5 # R:87/81/F=FE6 FE2 FE6 FE6 FE6 FE2 FE6 0 0 0 0 0 0 0 0 0  =E3C5**FAILED PROCESS REPLY**

S:90/3/12=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =942A/Q:4 # R:87/83/10=3432 3432 3432 3432 3432 3432 3432 0 0 0 0 0 0 0 0 0  =B0D0**FAILED PROCESS REPLY**

S:80/1/13=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =7237/Q:3 # R:97/81/11=FEB FD9 FE2 FEB FEB FEB FCC 0 0 0 0 0 0 0 0 0  =674**FAILED PROCESS REPLY**

S:80/3/14=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =58C5/Q:2 # R:97/83/12=3432 3432 3432 3432 3432 3432 3432 0 0 0 0 0 0 0 0 0  =2CE9**FAILED PROCESS REPLY**

S:90/1/15=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =BED8/Q:5 # R:87/81/13=FE6 FE2 FE6 FE6 FE6 FE2 FE6 0 0 0 0 0 0 0 0 0  =41C6**FAILED PROCESS REPLY**

S:90/3/16=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =C4FC/Q:4 # R:87/83/14=3432 3432 3432 3432 3432 3432 3432 0 0 0 0 0 0 0 0 0  =E006**FAILED PROCESS REPLY**

Rules:010000111=
S:80/1/17=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =22E1/Q:3 # R:97/81/15=FEB FD9 FE2 FEB FEB FEB FCC 0 0 0 0 0 0 0 0 0  =56A2**FAILED PROCESS REPLY**

S:80/3/18=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =A9BF/Q:2 # R:97/83/16=3432 3432 3432 3432 3432 3432 3432 0 0 0 0 0 0 0 0 0  =7C3F**FAILED PROCESS REPLY**

S:90/1/19=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =4FA2/Q:1 # R:87/81/17=FE6 FE2 FE6 FE6 FE6 FE2 FE6 0 0 0 0 0 0 0 0 0  =1110**FAILED PROCESS REPLY**

S:90/3/1A=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =3586/Q:0 # R:87/83/18=3432 3432 3432 3432 3432 3432 3432 0 0 0 0 0 0 0 0 0  =117C**FAILED PROCESS REPLY**

R:97/81/19=FEB FD9 FE2 FEB FEB FEB FCC 0 0 0 0 0 0 0 0 0  =A7D8**FAILED PROCESS REPLY**

R:97/83/1A=3432 3432 3432 3432 3432 3432 3432 0 0 0 0 0 0 0 0 0  =8D45
S:80/1/1B=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =D39B/Q:3 # R:87/81/1B=FE6 FE2 FE6 FE6 FE6 FE2 FE6 0 0 0 0 0 0 0 0 0  =E06A

S:80/3/1C=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =F969/Q:2 # Rules:000100111=
R:87/83/1C=3432 3432 3432 3432 3432 3432 3432 0 0 0 0 0 0 0 0 0  =41AA
S:90/1/1D=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =1F74/Q:1 # R:97/81/1D=FEB FD9 FE2 FEB FEB FEB FCC 0 0 0 0 0 0 0 0 0  =F70E

S:90/3/1E=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =6550/Q:4 # R:97/83/1E=3432 3432 3432 3432 3432 3432 3432 0 0 0 0 0 0 0 0 0  =DD93
S:80/1/1F=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =834D/Q:3 # SendInfluxdbPacket
Rules:000000011=Relay:0=1
Connected

Data: 267
Disconnected
R:87/81/1F=FE6 FE2 FE6 FE6 FE6 FE2 FE6 0 0 0 0 0 0 0 0 0  =B0BC

S:80/3/20=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =FD98/Q:2 # R:87/83/20=3432 3432 3432 3432 3432 3432 3432 0 0 0 0 0 0 0 0 0  =455B
S:90/1/21=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =1B85/Q:5 # R:97/81/21=FEB FD9 FE2 FEB FEB FEB FD0 0 0 0 0 0 0 0 0 0  =F3D9

S:90/3/22=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =61A1/Q:4 # R:97/83/22=3432 3432 3432 3432 3432 3432 3432 0 0 0 0 0 0 0 0 0  =D962
Rules:000000011=
S:80/1/23=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =87BC/Q:7 # R:87/81/23=FE6 FE2 FEB FE6 FE6 FE2 FE6 0 0 0 0 0 0 0 0 0  =3608

S:80/3/24=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =AD4E/Q:6 # R:87/83/24=3432 3432 3432 3432 3432 3432 3432 0 0 0 0 0 0 0 0 0  =158D
S:90/1/25=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =4B53/Q:5 # R:97/81/25=FEB FD9 FE2 FEB FEB FEB FD0 0 0 0 0 0 0 0 0 0  =A30F

S:90/3/26=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =3177/Q:8 # Rules:000000011=
R:97/83/26=3432 3432 3532 3432 3432 3432 3432 0 0 0 0 0 0 0 0 0  =9CD2
S:80/1/27=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =D76A/Q:7 # R:87/81/27=FE6 FE2 FE6 FE6 FE6 FE2 FE6 0 0 0 0 0 0 0 0 0  =E49B

S:80/3/28=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =5C34/Q:6 # R:87/83/28=3432 3432 3432 3432 3432 3432 3432 0 0 0 0 0 0 0 0 0  =E4F7
S:90/1/29=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =BA29/Q:9 # Rules:000000011=
R:97/81/29=FEB FD9 FE2 FEB FEB FEB FCC 0 0 0 0 0 0 0 0 0  =5253

S:90/3/2A=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =C00D/Q:8 # R:97/83/2A=3432 3432 3532 3432 3432 3432 3432 0 0 0 0 0 0 0 0 0  =6DA8
S:80/1/2B=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =2610/Q:11 # R:87/81/2B=FE6 FE2 FEB FE6 FE6 FE2 FE6 0 0 0 0 0 0 0 0 0  =97A4

S:80/3/2C=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =CE2/Q:10 # R:87/83/2C=3432 3432 3432 3432 3432 3432 3432 0 0 0 0 0 0 0 0 0  =B421
Rules:000000011=
S:90/1/2D=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =EAFF/Q:9 # R:97/81/2D=FEB FD9 FE2 FEB FEB FEB FCC 0 0 0 0 0 0 0 0 0  =285
S:90/3/2E=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =90DB/Q:12 # R:97/83/2E=3432 3432 3532 3432 3432 3432 3432 0 0 0 0 0 0 0 0 0  =3D7E
S:80/1/2F=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =76C6/Q:11 # R:87/81/2F=FE6 FE2 FE6 FE6 FE6 FE2 FE6 0 0 0 0 0 0 0 0 0  =4537

S:80/3/30=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =AEE1/Q:10 # Rules:000000011=
R:87/83/30=3432 3432 3432 3432 3432 3432 3432 0 0 0 0 0 0 0 0 0  =1622
S:90/1/31=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =48FC/Q:13 # R:97/81/31=FEB FD9 FE2 FEB FEB FEB FCC 0 0 0 0 0 0 0 0 0  =A086

S:90/3/32=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =32D8/Q:12 # R:97/83/32=3432 3432 3532 3432 3432 3432 3432 0 0 0 0 0 0 0 0 0  =9F7D
S:80/1/33=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =D4C5/Q:15 # SendInfluxdbPacket
Connected
Rules:000000011=

Data: 267
Disconnected
R:87/81/33=FE6 FE2 FEB FE6 FE6 FE2 FE6 0 0 0 0 0 0 0 0 0  =6571

S:80/3/34=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =FE37/Q:14 # R:87/83/34=3432 3432 3432 3432 3432 3432 3432 0 0 0 0 0 0 0 0 0  =46F4
S:90/1/35=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =182A/Q:13 # R:97/81/35=FEB FD9 FE2 FEB FEB FEB FCC 0 0 0 0 0 0 0 0 0  =F050

S:90/3/36=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =620E/Q:15 # R:97/83/36=3432 3432 3532 3432 3432 3432 3432 0 0 0 0 0 0 0 0 0  =CFAB
Rules:000000011=
S:80/1/37=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =8413/Q:14 # R:87/81/37=FE6 FE2 FE6 FE6 FE6 FE2 FE6 0 0 0 0 0 0 0 0 0  =B7E2

S:80/3/38=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =F4D/Q:13 # R:87/83/38=3432 3432 3432 3432 3432 3432 3432 0 0 0 0 0 0 0 0 0  =B78E
S:90/1/39=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =E950/Q:15 # R:97/81/39=FEB FD9 FE2 FEB FEB FEB FCC 0 0 0 0 0 0 0 0 0  =12A
S:90/3/3A=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =9374/Q:14 # Rules:000000011=
R:97/83/3A=3432 3432 3532 3432 3432 3432 3432 0 0 0 0 0 0 0 0 0  =3ED1
S:80/1/3B=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =7569/Q:15 # R:87/81/3B=FEB FE2 FEB FE6 FE6 FE2 FE6 0 0 0 0 0 0 0 0 0  =2D0
S:80/3/3C=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =5F9B/Q:14 # R:87/83/3C=3432 3432 3432 3432 3432 3432 3432 0 0 0 0 0 0 0 0 0  =E758
S:90/1/3D=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =B986/Q:13 # Rules:000000011=
R:97/81/3D=FEB FD9 FE2 FEB FEB FEB FCC 0 0 0 0 0 0 0 0 0  =51FC

S:90/3/3E=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =C3A2/Q:15 # R:97/83/3E=3432 3432 3532 3532 3432 3432 3432 0 0 0 0 0 0 0 0 0  =2BB3
S:80/1/3F=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =25BF/Q:14 # R:87/81/3F=FE6 FE2 FE6 FE6 FE6 FE2 FE6 0 0 0 0 0 0 0 0 0  =164E

S:80/3/40=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =6AF/Q:13 # R:87/83/40=3432 3432 3432 3432 3432 3432 3432 0 0 0 0 0 0 0 0 0  =BE6C
Rules:000000011=
S:90/1/41=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =E0B2/Q:15 # R:97/81/41=FEB FD9 FE2 FEB FEB FEB FD0 0 0 0 0 0 0 0 0 0  =8EE
S:90/3/42=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =9A96/Q:14 # R:97/83/42=3432 3432 3532 3532 3432 3532 3432 0 0 0 0 0 0 0 0 0  =A771
S:80/1/43=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =7C8B/Q:15 # R:87/81/43=FE6 FE2 FE6 FE6 FE6 FE2 FE6 0 0 0 0 0 0 0 0 0  =4F7A

S:80/3/44=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =5679/Q:14 # Rules:000000011=
R:87/83/44=3432 3432 3432 3432 3432 3432 3432 0 0 0 0 0 0 0 0 0  =EEBA
S:90/1/45=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =B064/Q:13 # R:97/81/45=FEB FD9 FE2 FEB FEB FEB FCC 0 0 0 0 0 0 0 0 0  =581E

S:80/1/46=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =B078/Q:15 # R:87/81/46=FE6 FE2 FE6 FE6 FE6 FE2 FE6 0 0 0 0 0 0 0 0 0  =8389

S:80/3/47=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =E237/Q:14 # SendInfluxdbPacket
Connected
Rules:000000011=

Data: 267
Disconnected
R:87/83/47=3432 3432 3432 3432 3432 3432 3432 0 0 0 0 0 0 0 0 0  =5AF4
S:90/1/48=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =DD3B/Q:13 # R:97/81/48=FEB FD9 FE2 FEB FEB FEB FCC 0 0 0 0 0 0 0 0 0  =3541

S:80/1/49=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =F54C/Q:15 # R:87/81/49=FE6 FE2 FEB FE6 FE6 FE2 FE6 0 0 0 0 0 0 0 0 0  =44F8

S:80/3/4A=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =8F68/Q:14 # R:87/83/4A=3432 3432 3432 3432 3432 3432 3432 0 0 0 0 0 0 0 0 0  =37AB
Rules:000000011=
S:80/1/4B=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =DD27/Q:15 # R:87/81/4B=FE6 FE2 FE6 FE6 FE6 FE2 FE6 0 0 0 0 0 0 0 0 0  =EED6

S:80/3/4C=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =F7D5/Q:14 # R:87/83/4C=3432 3432 3432 3432 3432 3432 3432 0 0 0 0 0 0 0 0 0  =4F16
S:90/1/4D=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =11C8/Q:13 # R:97/81/4D=FEB FD9 FE2 FEB FEB FEB FD0 0 0 0 0 0 0 0 0 0  =F994

S:80/1/4E=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =11D4/Q:15 # Rules:000000011=
R:87/81/4E=FE6 FE2 FE6 FE6 FE6 FE2 FE6 0 0 0 0 0 0 0 0 0  =2225

S:80/3/4F=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =439B/Q:14 # R:87/83/4F=3432 3432 3432 3432 3432 3432 3432 0 0 0 0 0 0 0 0 0  =FB58
S:90/1/50=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =2FEE/Q:13 # R:97/81/50=FEB FD9 FE2 FEB FEB FEB FCC 0 0 0 0 0 0 0 0 0  =C794

S:80/1/51=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =799/Q:15 # Rules:000000011=
R:87/81/51=FE6 FE2 FE6 FE6 FE6 FE2 FE6 0 0 0 0 0 0 0 0 0  =3468

S:80/3/52=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  =7DBD/Q:14 # `

I'm a litte confused... maybe you can help me?

> It has helped when timer for generating messages was increased to 12s - for my setup.

Ah, thanks, at which line/file can i change the timing?

**Comment by stuartpittaway** [comment]
**There are two things, which confuse me:**

**after installing the ESPControllerCode, only the first bank (bank0) is blinking through. The bank1 is not flashing...**

The controller settings have been reset when you programmed this version in - I suspect the number of banks is set to "1" in the web page.

**is it ok, if the ESP is not connected to the wifi (and the wifi-boot-webpage is shown), after flashing the esp?**

Yes - the latest version formats the ESP8266 controller SPIFFs storage space and that also wipes the settings on the first upload.  Just go through the initial configuration again and all is good.

**Comment by stuartpittaway** [comment]
Looking at the new trace, there are NO errors being reported by the controller.

You should see the controller requesting data S:80 and then S:90 - these are bank 0 and bank 1.

in your trace there is no S:90 so I assume that the setting isn't switched on for bank 1

**Comment by stuartpittaway** [comment]
Hello, the latest code has drastically changed the way data packets are sent and received, so I'm closing this issue - feel free to re-raise if the new code doesn't work for you.

**Comment by Klauzen** [comment]
Thanks Stuart! It is working now perfectly with the new code!
