### ISSUE TITLE
Current specs

### ISSUE THREAD

**Issue by mcelhennyi** [stuartpittaway/diyBMSv4#27]
Hey devs,

I came across DIY BMS on youtube, the other day. I am going to be starting a project shortly to make an EV go kart. I was contemplating using this BMS for my battery pack. 

I am trying to build a 300A 72v battery. Would this BMS be sufficient? I cant seem to find any specs in any issues or docs here.

EDIT: Additionally, would this bms support regenerative braking?

Thanks!

**Comment by stuartpittaway** [comment]
Hello, this BMS doesn't control the power/current into and out of the battery - its primary purpose is to monitor voltages, control relays based on rules (for safe shutdown for instance) and to balance cells.

As to wether its the right tool for your application, only you can decide as every setup and battery is different!
