### ISSUE TITLE
ATTINY841 missing in the BOM

### ISSUE THREAD

**Issue by maglub** [stuartpittaway/diyBMSv4#3]
The ATTINY841 is missing from the BOM

https://lcsc.com/product-detail/Others_Microchip-Tech_ATTINY841-SSU_Microchip-Tech-ATTINY841-SSU_C219103.html

**Comment by maglub** [comment]
It is also an item low on stock at LCSC. Currently only 7 pcs in stock

**Comment by maglub** [comment]
Alternative sources:

* (50 pcs) https://www.aliexpress.com/item/32949561717.html
* (10 pcs) https://www.aliexpress.com/item/33047987717.html

**Comment by stuartpittaway** [comment]
Thanks for the links.  I deliberately left the ATTINY out of the BOM as its very expensive from LCSC and easier to get hold off locally.
