### ISSUE TITLE
BOM Designator

### ISSUE THREAD

**Issue by Emu83** [stuartpittaway/diyBMSv4#30]
Hi Stuart,

Love the look of this BMS and in the process of getting some boards assembled (I know its DIY but I just don't have the time nor patients to do all that soldering!) and when I upload the BOM to the suppliers system it wont allow me to go any further as there is no "Designator" column.  Is this something you could send me please or upload to github?

Regards

**Comment by stuartpittaway** [comment]
Hello, if you take a look at the 4.2 branch the bill of materials files in there have the "designator" - it will look like R1 or C2 etc.  You will have to change the file to fit whatever your supplier wants.
