### ISSUE TITLE
In v4.2 R19 and R20 are in the wrong place

### ISSUE THREAD

**Issue by stuartpittaway** [stuartpittaway/diyBMSv4#34]
R19 (thermistor) and R20 (47k resistor) in the v4.2 branch are in the wrong location.

They should be reversed as the R19 part is near the ATTINY instead of in the shunt resistors.

**Comment by atanisoft** [comment]
@stuartpittaway was this also the case on 4.1?

**Comment by stuartpittaway** [comment]
Fixed in v4.21

**Comment by stuartpittaway** [comment]
@atanisoft if the R19 component is in the middle of the balance resistors then all is fine.

**Comment by atanisoft** [comment]
I'll need to check my jlc assembled boards. I don't remember looking at them very closely in this area.
