### ISSUE TITLE
CPL file for jlcpcb order

### ISSUE THREAD

**Issue by nathanrburgess** [stuartpittaway/diyBMSv4#35]
Which file do I upload to jlcpcb for the CPL file section?

**Comment by stuartpittaway** [comment]
For the modules - these are version 4.21 - the files are here

https://github.com/stuartpittaway/diyBMSv4/tree/Version4.2/Circuit

v4_bom_jlc.csv
v4_cpl_jlc.csv

and the Gerber files from https://github.com/stuartpittaway/diyBMSv4/blob/Version4.2/Circuit/gerber/gerber.zip
