### ISSUE TITLE
NCP18WB473J03RB out of stock on jlcpcb

### ISSUE THREAD

**Issue by Gokalex** [stuartpittaway/diyBMSv4#36]
https://jlcpcb.com/parts/componentSearch?searchTxt=NCP18WB473J03RB

Is there an alternative?

**Comment by stuartpittaway** [comment]
Not really, probably best to wait for it to come into stock.

You could swap to CMFA104F4150HANT but then you also need to change R20 to 100Kohm resistor as well - it won't work properly if you don't swap that.

**Comment by stuartpittaway** [comment]
Hello, replaced the part with NCP15WB473F03RC (0402 size) as part of check in 05ff45a
