### ISSUE TITLE
missing components JLCPCB

### ISSUE THREAD

**Issue by jopimo** [stuartpittaway/diyBMSv4#37]
Hi

It's possible change this items outs of stock to other ones ?
 **R19**
Original -> C86142    ( 4,7K +- 1% 4050 K +-1%  100 mW )
Remplace ->  C77128 ( 4,7K +-0.5%. 4050 K +-5% 100 mW )
**D1**
Original -> C84139  ( 1,25V 18V 100 mA 20ppm/Cº )
Remplace -> C171461  (1,25V 15V 50 mA  50 ppm/Cº )

Thanks in advance

**Comment by stuartpittaway** [comment]
Those items seem sensible replacements, but I obviously can't guarantee it!
