### ISSUE TITLE
wrong part placement

### ISSUE THREAD

**Issue by lzahradil** [stuartpittaway/diyBMSv4#38]
wrong part placement, see photo

https://photos.app.goo.gl/Kuum7UuNb5fmXFmF7

**Comment by stuartpittaway** [comment]
This was fixed yesterday, please download latest version

**Comment by lzahradil** [comment]
i have a pcb in production where it was fixed.

controller board is the following problem: 

Designator | Assemble | Part # | Comment | Footprint | Warning
-- | -- | -- | -- | -- | --
U3 | Yes | C7605 | NXP Semicon PCF8574T/3,518 | SOIC-16_7.5x10.3x1.27P | Soldering area is too small
