### ISSUE TITLE
Request for new relay rule

### ISSUE THREAD

**Issue by wurstyboy** [stuartpittaway/diyBMSv4#4]
Many battery chargers/inverters have inputs which can be connected to a BMS.
Typically over voltage and over temperature of single packs is used for these AUX channels.
Also under voltage of a single pack is missing as a rule.

So it would be nice to have a **new rule.**

I would recommend the following rule:
**"4. Individual cell under voltage (mV)"
Standard value : 3000**

Also it would add unit for 2. (mV) and 3. (°C)

Thanks,
Sebastian

**Comment by stuartpittaway** [comment]
Implemented
