### ISSUE TITLE
NTC value

### ISSUE THREAD

**Issue by gen-ben** [stuartpittaway/diyBMSv4#40]
hello,
Can I use different NTC type (10k) for external temperature readings?
If not, I would like to change both the external and internal sensors, what changes should I make to read the temperature correctly using 10k NTC?

**Comment by stuartpittaway** [comment]
It should be possible, you need to stick with NTC thermistors and ideally 4050K

If you plan to use 10k NTCs then you also need to change resistors R21 and R20 to 10k. This covers both internal and external sensors.

**Comment by gen-ben** [comment]
Is there any changes needed in code?

**Comment by stuartpittaway** [comment]
No code changes should be required.

**Comment by gen-ben** [comment]
OK thank you 👍 :)
