### ISSUE TITLE
Please add polarity markings to silkscreen

### ISSUE THREAD

**Issue by stienman** [stuartpittaway/diyBMSv4#43]
After placing an order with jlcpcb, I received a request to confirm polarity of diodes and other parts. I checked the schematic and confirmed this with them, but it would be nice if the silkscreen included polarity, particularly for two pin polarized parts such as D2, D3, and D4.

“ Well got your order with many thanks~

Sorry to bother you, but there is one thing that we want to confirm with you about your SMT order before proceeding.

As shown below, we are not so sure about the polarity for the components below is correct or not, could you please kindly have a check?

Can we just make it as shown in the picture?”

![8AC76F45-C961-4B5C-83BD-A99B04C58A1D](https://user-images.githubusercontent.com/2047613/87000606-7e2d5c80-c183-11ea-83bc-aad676688e39.png)

**Comment by stuartpittaway** [comment]
Thanks, this has now been completed and new files available in github branch.

**Comment by stienman** [comment]
Thanks for doing this, and so quickly!  I really appreciate your work on this project.
