### ISSUE TITLE
jlcpcb DFM Check found error on Controller PCB

### ISSUE THREAD

**Issue by SvenSFS** [stuartpittaway/diyBMSv4#44]
Hi 
i have order the Controller and the BMS V4.21 on JLCPCB.

In production Process fount the DMF an Error on U3 -> Soldering area is too small
Thanks for the great project.

![Unbenannt](https://user-images.githubusercontent.com/8532533/87253575-94396680-c47c-11ea-8ce3-772c51118149.png)

**Comment by stuartpittaway** [comment]
Hello, thanks for raising this issue.  We've had several hundred boards produced using the same GERBER files at JLCPCB !

The footprint looks fine to my eyes.  Perhaps delete your order and try again!

**Comment by SvenSFS** [comment]
The job can be cancelled. it is in producion. 
i will test that.

I don't see any difference in the picture. but jlcpcb corrected that.

did someone else report this error?

**Comment by atanisoft** [comment]
the footprint is set to SO-16-W and should be SOIC-16W, they are very similar but slight differences in the footprint (7.0mm vs 7.5mm on length)

**Comment by stuartpittaway** [comment]
Nobody else has had the same problems!

Good spot on the solder pad sizes, I'll leave this issue open. As a reminder

**Comment by stuartpittaway** [comment]
This is now fixed in the JLCPCBASSEMBLY branch.  Thanks for reporting.
