### ISSUE TITLE
Question: Different ATtiny841-SSU between ATTINY84A-SSU 

### ISSUE THREAD

**Issue by SvenSFS** [stuartpittaway/diyBMSv4#45]
is it possible to take the ATTINY84A-SSU?
the ATtiny841-SSU is hard to come by.

According to the document, the pin is compatible and has the same functions.
The price is the same in Germany

[Atmel-8495-8-bit-AVR-Microcontrollers-ATtiny441-AT-1315526.pdf](https://github.com/stuartpittaway/diyBMSv4/files/5011795/Atmel-8495-8-bit-AVR-Microcontrollers-ATtiny441-AT-1315526.pdf)
[ATTINY24A-44A-84A.PDF](https://github.com/stuartpittaway/diyBMSv4/files/5011796/ATTINY24A-44A-84A.PDF)

**Comment by stuartpittaway** [comment]
No has to be the correct chip, they are different internally

**Comment by Jestergnet** [comment]
sorry, but the translator has not translated it unambiguously. Is this question also interested, yes or no?

**Comment by Jestergnet** [comment]
> 
> 
> No has to be the correct chip, they are different internally

sorry, but the translator has not translated it unambiguously. Is this question also interested, yes or no?

**Comment by stuartpittaway** [comment]
Diybms only works with the ATtiny841-SSU

**Comment by Jestergnet** [comment]
> 
> 
> Diybms only works with the ATtiny841-SSU

Now understand. Thanks! It's a pity, the nonsense ordered ATTiny84a.
