### ISSUE TITLE
ATTINY programming

### ISSUE THREAD

**Issue by jency001** [stuartpittaway/diyBMSv4#46]
HI Stuart,

I am building your DIY bms but got stuck on the programming of the attiny.
i programmed the wemos alread that worked great. but for the cellmoduel i do not have an usb isp programmer.
i tried using an arduino and already look at several place on how to doe this but i did not have any luck.
Do you have an instruction on how to program the cellmodule with an arduino or someone that explains this very clearly.

Kind Regards

**Comment by stuartpittaway** [comment]
Does this guide help?

https://www.microcontrollertips.com/programming-avr-microcontrollers-arduinos-arduino-isp/

You would use a spare Arduino Uno as a programming device.

**Comment by jency001** [comment]
i already turned my arduino in an isp programmer with the steps you mentiond but its the next step i am stuck with.
so no i tought i need to open visual studio code again and just upload the attiny v400 to it but i fails.
 
![image](https://user-images.githubusercontent.com/25853633/89737943-4ca2fc00-da75-11ea-803d-1c26401c8ecf.png)

**Comment by stuartpittaway** [comment]
It's still trying to use usbasp programmer. Take a look at platformio.ini file and change usbasp to arduinoisp

**Comment by jency001** [comment]
oke will try that . ill let you know if it works

**Comment by jency001** [comment]
oke this got me one step further. i will try again tomorrow.
![image](https://user-images.githubusercontent.com/25853633/89739990-91369380-da85-11ea-851f-81459bfd0561.png)
![image](https://user-images.githubusercontent.com/25853633/89740019-c511b900-da85-11ea-9d31-590d29cfd1d5.png)

**Comment by stuartpittaway** [comment]
You probably just need to tell platformio what com port to use.

**Comment by jency001** [comment]
where do i fill this in i cant find it in the code.

**Comment by stuartpittaway** [comment]
This should help...

https://docs.platformio.org/en/latest/projectconf/section_env_upload.html

**Comment by jency001** [comment]
I tried changing the comport instead. Still same result. I will try to add the code tomorrow.
But I looked up the error code. It's something about the bootloader. Do I need to burn a bootloader first trough the arduino ide ?

**Comment by stuartpittaway** [comment]
No the modules don't have a boot loader.

Are you using the upload using programmer option in platformio instead of the upload option?

**Comment by jency001** [comment]
I do it the same way like for the wmos. I watched your video on how to upload the code. Open the program. Make workbook or something like that can't remember the correct term right know. The click on the alien head go to the v400 and click upload.

**Comment by stuartpittaway** [comment]
If you are using Arduino programmer try upload using programmer instead of upload.

**Comment by jency001** [comment]
No still no succès. I will try it tomorrow with an USB asp.

**Comment by jency001** [comment]
hi Stuart,

so i tried again with an ATMEL-ice programmer. but still no success in visual studio. but i took the hex file generated from visual studio and uploaded it with Atmel studio and this worked fine. but i still have no idea whats wrong wit visual studio.
![image](https://user-images.githubusercontent.com/25853633/89873982-80883980-dbbb-11ea-8079-c99b239e7dd8.png)

**Comment by karciok** [comment]
Hi,
I think, that I figured out the problem.
In platformio.ini you need to add those 4 lines under upload flags

  -P$UPLOAD_PORT
  -b$UPLOAD_SPEED
upload_port = COM4   ;change COM4 to whatever port your arduino shows up as
upload_speed = 19200

and change 

upload_protocol = stk500v1

it worked for me, hope it helps anyone.
