### ISSUE TITLE
Missing BOM and whatever that other file is

### ISSUE THREAD

**Issue by Michaelillingby** [stuartpittaway/diyBMSv4#54]
So I am trying to order the PCB for the V4 since I am pretty sure thats the one I should be getting, but the zip file doesnt contain the files you mention in the walkthrough video. there IS a bom on the root folder of that zip but it has a different name (CellModules_LCSC_BillOfMaterials.xls) 
Id really like to order these ASAP so can you please provide the files I need to place my order?
michael.i@me.com

**Comment by stuartpittaway** [comment]
Hello, the V4 board is for manual assembly and doesn't include the BOM or CPL files.

If you want JLCPCB to build the boards for you - use the V4.21 branch of the code from here

https://github.com/stuartpittaway/diyBMSv4/tree/jlcpcbassembly/Circuit

The three files you need are:
v4_bom_jlc.csv
v4_cpl_jlc.csv
gerber.zip
