### ISSUE TITLE
TL432G-A-AE3-R is no longer available on JLCPCB

### ISSUE THREAD

**Issue by stuartpittaway** [stuartpittaway/diyBMSv4#56]
Update BOM with replacement for TL432G-A-AE3-R

**Comment by moscito1010** [comment]
Indeed?
Then github has probably not updated yet. I'll look again tomorrow.

**Comment by stuartpittaway** [comment]
I've not made any changes this is just a reminder ticket to fix it.

**Comment by moscito1010** [comment]
lol, Sorry I missed that.
I have one more request, but that would go beyond the scope here.

Am So., 13. Dez. 2020 um 21:14 Uhr schrieb Stuart Pittaway <
notifications@github.com>:

**Comment by stuartpittaway** [comment]
Changed to part TL432, C171428, now 1.24V reference instead of 1.25V

https://lcsc.com/product-detail/Voltage-References_Shikues-TL432_C171428.html/?href=jlc-SMT
