### ISSUE TITLE
Excesive imput impedance for ADC readings

### ISSUE THREAD

**Issue by wild-mustango** [stuartpittaway/diyBMSv4#64]
Hello Stuart, I've come across your diyBMS and I want to help, not only in your HW but also in your SW design.
I am a HW and SW engineer. For now, I have started to review the circuit for the **Cell Monitoring Module Rev 4**. The file I've opened is [Schematic](https://github.com/stuartpittaway/diyBMSv4/blob/master/Circuit/circuit.pdf) I hope it is your latest revision.

Just to confirm, I also opened [source_code](https://github.com/stuartpittaway/diyBMSv4Code/blob/master/ATTINYCellModule/src/diybms_attiny841.cpp) and  checked _PB2 = ADC8 PIN 5 ARDUINO PIN 2/A8 = VOLTAGE reading_ that your are using PB2 to read voltage using a voltage divider.

For a correct reading of voltage, the impedance seen by the ADC pin, Microchip recomends a maximum if 10k output impedance (datasheet page 139). You are using R3=475k and R4=402k resistors. The impedance seen by the input pin is the parallel equivalent resistance, which is around 217k, far away from 10k. I think you (as I did in the past) used these high values to lower the current consumption, but this may be affecting the voltage reading. I'm used to PIC18 from Microchip also and had reading innaccuracies due to this problem.

Solutions:

1. Reduce R4 resistor to have a parallel equivalent resistance lower than 10k, that is, any resistor lower than 10k, e.g. 4k7. Check the accuracy of the readings regarding the 10bit resolution. Using R4=4k7 and R3=475k and 4.458V as max, will result in a max current of 9.3 uA.
2. Should you stilll get inaccuracies, you may want to use R3 and R4 lower resistance values, to increase a bit the current throught the resistors. Since you are using an enable pin to source the voltage divider whenever you want, you control the amount of current by controlling how many times and how long you enable this pin.

I hope this helps.

I am willing to collaborate in this project. Should you have any Discord channel or any other active group to talk, please let me know.

Kind regards

**Comment by stuartpittaway** [comment]
Thank you for the feedback, there is an active group on the openenergymonitor forum.

The latest design is 4.21, this is on the jlcpcbassembly branch on GitHub.

From memory I think I reduced those resistor values, but will check. I had also read about the input impedance of 10K, however so far, I've had rock solid readings in the 2 years I've been using that design. I think as I'm also running the attiny at a slow clock rate and also sampling the ADC at a slow rate, plus using the low noise software settings, it's worked out ok.

**Comment by stuartpittaway** [comment]
Just to add, we've recently seen trouble with the TL432 chip used in the newer design, looks likely down to poor quality control at manufacturer.

Perhaps you have another low cost voltage reference we can consider?

**Comment by stuartpittaway** [comment]
I've looked a tthe V4.21 design (located here https://github.com/stuartpittaway/diyBMSv4/tree/jlcpcbassembly/Circuit)

This is using 68K and  27K resistors for the divider, and a reference voltage of 1.25V - using a TL432 current shunt.

**Comment by wild-mustango** [comment]
Thanks for the quick response!!  With those res values, Rparallel is around 20k, a bit higher than recommended, but since you haven't had any problems, that's perfect (:

Regarding to the Voltage Reference, I have no experience with these devices but I talked to a friend of mine used to work with them. He told me about TL432 and a better choice: LM4040. He told me that TL432 should be used together with a 10 or 100 nF (better) decoupling cap in parallel [Parallel Capacitor](https://www.ti.com/lit/wp/slpy003a/slpy003a.pdf?ts=1611931195962&ref_url=https%253A%252F%252Fwww.google.com%252F) page 3. As he mentioned, TL432 has been always a good solution cheaper thant the **LM4040**, but both perform well, in his words.

I have done a quick Mouser search and barely seen a significant difference in prices, at first glance, around 0.55€. What's your price range for "low cost" you mentioned? Choosing chepaest asian brands (0.1€) may result in tolerances in manfucturing of parts. It is always a better idea to spend a little more on brands like TI for the same part number. I know for a DIY to adjust BOM cost at maximum is a goal, but maybe this component may no be the case.

Since I'm new to this voltage references, I am now reading some papers.

I don't really know what's the main problem you are experiencing with your voltage reference, do you have these problems posted in the forum?

Have you written down your specs required for the voltage reference?: 
- **VREF:** I see you chose 1.25V (why this low value?)
- **VIN range:** (voltange seen by the cathode) I think this depends on the SOC of the battery cell
- **Initial accuracy:** 
- **current drive**
- **power consumption**
- **Temperature range** (Temperature coefficient)
- **Package size**

In the mean time, I'm going to have a deep read on the forum thread you gave me starting from the last post so I can join the conversation there.

Regards

**Comment by stuartpittaway** [comment]
Hi, the original design used the LM4040 chips, and they worked fine, they are more expensive than the TL432 (about 10x!)

The VIN range is determined by the chemistry of the battery cells, normal lithium 18650, 0-4.2V (some are 4.35V).

However to cater for lower chemistry voltages like LTO 0-2.4V

The ATTINY works fine down to 1.8V, and is run directly from the cell its connected to.  The voltage reference of 1.25V was picked as a lot of voltage references stop working when the input voltage drops below reference + 0.5V (approx).  We saw this on the LM4040, I was using a 2.048V reference, and this fails at about 2.4V input - which isn't good for LTO cell monitoring.

Ideally, I've been trying to use 1% components for accuracy, although ultimately we are stuck with a 10bit ADC on the ATTINY.

**Comment by stuartpittaway** [comment]
A quick update, the newer V4.40 boards use 6.8k and 2.7k resistors to provide a lower impedance for the ADC.
