### ISSUE TITLE
Parts library missing for the controller

### ISSUE THREAD

**Issue by poberth** [stuartpittaway/diyBMSv4#71]
Great job for new release of the controller.

I tried to open the project in kicad 5.1.9 and it is missing the ControllerCircuit.lib so the K1, K2, LCD1, U3, U4 and U5 parts are missing in the schematic. The ESPControllerCircuit project is also missing the schematic library so the wemos part is not loading up.

Could you provide the libraries so that every parts are available in the projects.

Thanks and keep up the good work.

**Comment by stuartpittaway** [comment]
Ah - how strange I must have missed those off.

I've uploaded into master branch now.
