### ISSUE TITLE
v4.4 module D2 rotate issue?

### ISSUE THREAD

**Issue by atanisoft** [stuartpittaway/diyBMSv4#73]
Just checked the DFM output from JLCPCB for the v4.4 module PCBs and found the following differences:
Original:
![Produce_DanZhi SMT_Original_Snapshot Top 2674510F_Y47 SMT0210309156967](https://user-images.githubusercontent.com/6457044/110820174-b79ef600-8243-11eb-8bd5-4537be2003d2.png)
Modified:
![Produce_DanZhi SMT_Snapshot Top 2674510F_Y47 SMT0210309156967](https://user-images.githubusercontent.com/6457044/110820201-bec60400-8243-11eb-81dd-b4c3e41ab530.png)

It appears that D2 is rotated 180deg.

**Comment by stuartpittaway** [comment]
Hi Mike.

I think JLC have this WRONG - the "stripe" of the TVS diode needs to be facing towards the right handside of the board (towards positive).  

![image](https://user-images.githubusercontent.com/1201909/110824866-5ac72e00-828b-11eb-94cd-ed1933110b3f.png)


![image](https://user-images.githubusercontent.com/1201909/110824218-c3fa7180-828a-11eb-947e-510e60de6bc5.png)

**Comment by stuartpittaway** [comment]
I used this reference when building the circuit for the TVS... https://www.mouser.com/pdfdocs/AND8424-D.PDF

**Comment by atanisoft** [comment]
> I think JLC have this WRONG - the "stripe" of the TVS diode needs to be facing towards the right handside of the board (towards positive).

Possibly, but usually they use "-" to indicate the stripe/marking on the diodes. If I receive them reversed I'll rotate it. But wanted to log this issue just in case it is in fact incorrect on the CPL file.

**Comment by stuartpittaway** [comment]
This is the reference circuit.

![image](https://user-images.githubusercontent.com/1201909/110827523-10937c00-828e-11eb-8ddd-afde0b198e90.png)

and mine (note ground is on top, so flipped image)

![image](https://user-images.githubusercontent.com/1201909/110827588-21dc8880-828e-11eb-81af-60c9d176a737.png)


I've just stolen this from https://www.quora.com/How-do-I-identify-a-TVS-diode

> A TVS diode will be connected directly across a supply rail (+5V or +12V), sometimes with a series inductor, fuse, polyswitch, or zero-ohm resistor. 
> **The anode of the diode goes to ground, while the cathode (striped end) connects to the positive supply rail.** 
> TVS diodes will usually be located near the power connector, but not always.
> 

I think JLC have this part recorded as a "standard" diode, so it looks backwards to them.

**Comment by atanisoft** [comment]
Ok, as noted I'll check the boards when they arrive to confirm the orientation and adjust if required. 

We may need to get a note in the CPL/BOM file for JLCPCB to ensure proper rotation.

**Comment by stuartpittaway** [comment]
Looks like JLC have told another user that the part placement is wrong as well.

Why do they care!!  I can understand if the placement was wrong or the foot print wrong!

**Comment by stuartpittaway** [comment]
I'm starting to doubt myself on this now, I've checked that diagram so many times

**Comment by stuartpittaway** [comment]
Think I've found the issue, I'm not rotating the part in KICAD however when the CPL/BOM files are generated by a script, its adding in a 180 rotation.

**Comment by atanisoft** [comment]
Great, so as long as the part is correctly placed as the band to the + side (towards edge of board) it should work?

**Comment by stuartpittaway** [comment]
Yes that's right. If it's the other way, it will be a dead short!

**Comment by atanisoft** [comment]
Gotcha, I'll confirm before testing/flashing/etc. Hopefully I'll have the boards in a bit over a week. I'll also use six jumper wires to test flashing from the ESP32 controller.

**Comment by stuartpittaway** [comment]
Forum posts have indicated that this image/placement

![image](https://user-images.githubusercontent.com/1201909/111316672-5fa92a80-865b-11eb-83d9-e35a60e00964.png)

results in a board being made like this

![image](https://user-images.githubusercontent.com/1201909/111316804-7a7b9f00-865b-11eb-9a96-ac4a0c9c3ff1.png)

**THIS IS INCORRECT, SO ENSURE THE PREVIEW IMAGE SHOWS NEGATIVE ON THE RIGHT HAND SIDE**

**Comment by Paragon35** [comment]
Hi, Stuart I got  modules from JLCPCB where D2 has a cathode stripe (-) gray stripe is on the left and an anode (+) without stripe is on the right so is it ok?

![19](https://user-images.githubusercontent.com/81571399/113503084-ef8e1600-952f-11eb-92b6-a2e0531f1ad3.jpg)

**Comment by stuartpittaway** [comment]
No that's incorrect.  Do not power up these boards before fixing the issue.

Two options

Unsolder and remove the part

Or

Unsolder and rotate, solder back on.


The part is quite large, so not difficult to do.

**Comment by Paragon35** [comment]
> 
> 
> No that's incorrect. Do not power up these boards before fixing the issue.
> 
> Two options
> 
> Unsolder and remove the part
> 
> Or
> 
> Unsolder and rotate, solder back on.
> 
> The part is quite large, so not difficult to do.

thanks so when JLCPCB wanted to turn the element unnecessarily I told them to leave them as in the original :)
I will turn around, no problem, as you write it is a big element, thanks again and best regards

![1](https://user-images.githubusercontent.com/81571399/113503269-0c771900-9531-11eb-9e76-b7ae7ba1431b.JPG)

**Comment by stuartpittaway** [comment]
How long ago did you order these? I changed the silkscreen a few weeks ago to help jlc orient the part correctly

**Comment by Paragon35** [comment]
> 
> 
> How long ago did you order these? I changed the silkscreen a few weeks ago to help jlc orient the part correctly

Stuart, order from 2021-03-10

as you can see in the picture I pasted above, JLCPCB wanted to correct the cathode (-) on the right side, it's my fault because I insisted they leave as in the original where the cathode (-) is on the left side

**Comment by SP3S** [comment]
https://user-images.githubusercontent.com/62333994/231421323-ccdf93c0-a129-4373-8495-a3a33c1abfde.png
