### ISSUE TITLE
DIYBMS Controller V 4.2

### ISSUE THREAD

**Issue by Paragon35** [stuartpittaway/diyBMSv4#77]
hey Stuart, today the controller got to me and I have such doubts if you could spread it :) ..
Your controller in the selected two sections has soldered elements:

![1](https://user-images.githubusercontent.com/81571399/112845026-a9a2ff00-90a4-11eb-987a-b35a14c2891b.JPG)

that are not on the JLCPCB controller if this is a problem, 

![2](https://user-images.githubusercontent.com/81571399/112845105-c8a19100-90a4-11eb-9734-2aa61417e156.jpg)

I checked the parts list before ordering and they were all, greetings from Poland Leszek ....

**Comment by stuartpittaway** [comment]
What you have is correct, and the latest version - none of those parts are in use.  

I've removed the TX2 and RX2 port from future revisions of the board.

**Comment by Paragon35** [comment]
> 
> 
> What you have is correct, and the latest version - none of those parts are in use.
> 
> I've removed the TX2 and RX2 port from future revisions of the board.

Thanks Stuart, the project is really impressive. Congratulations, I'm picking up the parts with parcels. Modules have not arrived yet, thanks again and best regards Leszek
