### ISSUE TITLE
New controller uses TCA6408AQPWRQ1 which is not suitable for 5V operation

### ISSUE THREAD

**Issue by stuartpittaway** [stuartpittaway/diyBMSv4#78]
Circuit should use TCA6408APWR not TCA6408AQPWRQ1 for part U3.

TCA6408AQPWRQ1 is automotive grade, and rated for 3.3V on pin 16, not 5V.

Existing chips do appear to work, although over specification

Correct part number from LCSC is C206177

**Comment by Paragon35** [comment]
> 
> 
> Circuit should use TCA6408APWR not TCA6408AQPWRQ1 for part U3.
> 
> TCA6408AQPWRQ1 is automotive grade, and rated for 3.3V on pin 16, not 5V.
> 
> Existing chips do appear to work, although over specification
> 
> Correct part number from LCSC is C206177

Stuart, will this one be good?
https://pl.aliexpress.com/item/1005001786862072.html
