### ISSUE TITLE
[Kicad] Missing Libraries like: EL3H7-G.lib

### ISSUE THREAD

**Issue by hitech95** [stuartpittaway/diyBMSv4#8]
I'm tring to open the project but looks like that the libraries are missing.
I'm new on Kicad so I might do something wrong.

Steps to reproduce:
1) Download & Install Kicad
2) Open the project
3) Tell Kicad to add the Simbols to the default library
4) Open the schematic
5) Get an error, files open but all symbols are missing

**Comment by stuartpittaway** [comment]
Which version of kicad did you install?

**Comment by hitech95** [comment]
I have installed Kicad 5.1.14

**Comment by phisp** [comment]
I had a missing Libraries issues with an older version of Kicad too. I installed 5.1.4 and it worked fine.

**Comment by hitech95** [comment]
> 
> 
> I had a missing Libraries issues with an older version of Kicad too. I installed 5.1.4 and it worked fine.

I probably need some default libray, that so far is not loaded. (Or at least I think)
I'm recreating the project on Altium so I can use a CAD that I know, but I would have preferred to use Kicad if the project was loading correctly.

**Comment by phisp** [comment]
Go to Preferences -> Manage Symbol Libraries -> Project Specific Libraries
Delete si8631ab-b-is1 and EL3H7-G these parts are not needed anymore.
The EL3H7-G has probably been replaced by the HMHA2801.
The ESPCircuit needs the Wemos D1 Mini from https://github.com/rubienr/wemos-d1-mini-kicad
to be completed. However it is not need either.

**Comment by hitech95** [comment]
> Go to Preferences -> Manage Symbol Libraries -> Project Specific Libraries
> Delete si8631ab-b-is1 and EL3H7-G these parts are not needed anymore.
> The EL3H7-G has probably been replaced by the HMHA2801.
> The ESPCircuit needs the Wemos D1 Mini from https://github.com/rubienr/wemos-d1-mini-kicad
> to be completed. However it is not need either.

Done but the schematic still have a lot of '???' instead of the symbols. Resistors, caps, all all marked with ?

**Comment by hitech95** [comment]
Looks like I had a corrupted installation of KiCad!
