### ISSUE TITLE
TJA1057GT/3J

### ISSUE THREAD

**Issue by trebor1508** [stuartpittaway/diyBMSv4#83]
is a shortage of this element in jlc and everywhere. can be replace by other available chip?

**Comment by atanisoft** [comment]
IFX1050GVIO should be a drop in replacement, but it is also likely backordered from most suppliers.

You can also omit this chip safely if you are not planning on using the CAN bus for taking to a charge controller etc.

**Comment by trebor1508** [comment]
For what purpose this communication can be used? I have a victron equipment. 
Or i think i can solder manually later on when this chip will be available.

**Comment by stuartpittaway** [comment]
It can be added later on without a problem - its not currently used by the software so you won't miss any functionality (at the moment).

I've spoken with JLC and they have said there should be some arriving this week - but I've been told that before.

**Comment by stuartpittaway** [comment]
Parts which can be used:

IFX1050GXUMA1 = C129255
TJA1057GT/3J = C112947
TJA1051TK/3 (no longer available from JLCPCB)

On the TJA range - the import part is the "/3" - indicating its 3.3V compatible.

At the time of writing, JLC have very little stock of the above.

Looking at other sites, all are out of stock (Farnell/Mouser etc.)

**Comment by trebor1508** [comment]
I have check for C112947 all available sources and nothing.

https://b2b.partcommunity.com/3d-cad-models/sw-push-6mm-h5mm-kicad?info=kicad%2Fbutton_switch_tht2e3dshapes%2Fsw_push_6mm_h5mm.prj&cwid=8655
this kind push button?

Yes I will be ordering now.  So i will try 4,3

about Farnell, part of group called CPC is located 1miles from my home location (Preston) :)

Thanks Stuart

**Comment by stuartpittaway** [comment]
That button should be good. Just a word of warning, this is a new revision but nothing major has changed, but I've also not fully tested it!

**Comment by trebor1508** [comment]
So it will be a test, I will order 5 fully asembled (difference in price is about 10F)

**Comment by trebor1508** [comment]
Stuart. Jlc said "The orientation of the component does not match the pad" on controller board. But i do not see any changes.

**Comment by fhorst1** [comment]
I'm a bit confused.
The new version controler can "talk" CANBUS? Or not yet?

For me the communication with canbus was / is the reason to switch over to the new controller version.

Due to problems with parallel, I now have my setup all series, and need 5* controller, 80x cell modules.
Not a problem, I have.

My 3 hybrid inverters have only CAN as communication protocol for the BMS.
Not sure how it can actively assist the charge controller, that is something to find out once installed :-)

Would be nice if it already can do CAN :-)

**Comment by stuartpittaway** [comment]
The CAN hardware is on the controller board, but the software has not been written to talk CAN - yet.

What inverters do you have?

**Comment by stuartpittaway** [comment]
> Stuart. Jlc said "The orientation of the component does not match the pad" on controller board.
> F1
> But i do not see any changes.

Thanks @trebor1508 - I changed the size of the pad for the fuse (F1) as JLC kept saying it was too large - the part cannot be oriented incorrectly as it doesn't have a polarity.

Can you upload the pictures they send you (or you can logon to the JLC account to see them)

**Comment by fhorst1** [comment]
I found the communication protocol.

Can't seem to be able to attach PDF here, so I did it in OEM forum

**Comment by trebor1508** [comment]
![Screenshot_2021-05-20-08-58-38](https://user-images.githubusercontent.com/77877722/118941798-022aa600-b94a-11eb-8865-fbe18ae3d94d.png)
![Screenshot_2021-05-20-08-58-02](https://user-images.githubusercontent.com/77877722/118941799-035bd300-b94a-11eb-850e-aff5947989b0.png)

**Comment by stuartpittaway** [comment]
> I hope this helps

It looks identical to me as well !

**Comment by trebor1508** [comment]
They mention about resistor R3 but R1 and R4 looks identical. 
F1 should be good as well.

**Comment by stuartpittaway** [comment]
@trebor1508 think I've spotted an issue with the controller board - U9 and U12 are rotated incorrectly, this will need to be fixed after delivery/build of your order - unless you can cancel now.

**Comment by trebor1508** [comment]
I can not cancel now. But it is only 4 leg chip. I think i can fix it when they arrived.

**Comment by trebor1508** [comment]
Stuart

> @trebor1508 think I've spotted an issue with the controller board - U9 and U12 are rotated incorrectly, this will need to be fixed after delivery/build of your order - unless you can cancel now.

check the photo what I upload, JLC rotate U9 and U12. So I do not have to do anything.

**Comment by stuartpittaway** [comment]
Great, should be good to go then.

**Comment by trebor1508** [comment]
> Great, should be good to go then.

I placed my order yesterday.

**Comment by trebor1508** [comment]
one more simple question: Switch SW1 and SW2 how many milimeters are between legs?

**Comment by stuartpittaway** [comment]
This is the part the footprint is based on

https://www.mouser.co.uk/ProductDetail/CK/PTS645SL502LFS?qs=UxeAxwACbqm88cEAxDT3kg==

It's fairly generic foot print, think it's 6mm spacing, but check datasheet

**Comment by trebor1508** [comment]
Is here someone from UK who order from JLC recently?  I have choose DHL and they sent me a message to pay £45 import tax. But on JLC was on order over £135 will be no tax. 
£158 order with postage €45 tax. SWEET. Bloody BREXIT.

**Comment by stuartpittaway** [comment]
When you order there is another. Option to use DHL with prepaid tax, either way you have to pay vat at 20%

The message on jlc website is incorrect

**Comment by trebor1508** [comment]
I received my order from JLCPCB

I have solder the first controler and is working fine. 

![20210602_231024](https://user-images.githubusercontent.com/77877722/120559096-5036b380-c3f8-11eb-9879-6a9ff2a2fe52.jpg)
SD CARD socket is not so good.

![20210602_231301](https://user-images.githubusercontent.com/77877722/120559276-ae639680-c3f8-11eb-8ca2-77979a7ded7f.jpg)
![20210602_231244](https://user-images.githubusercontent.com/77877722/120559302-b91e2b80-c3f8-11eb-8b0a-042dbed91365.jpg)

**Comment by trebor1508** [comment]
![20210601_215411](https://user-images.githubusercontent.com/77877722/120559420-e965ca00-c3f8-11eb-91a3-b90cade7e1e0.jpg)
Is this fine? Or cable color is reversed?

**Comment by atanisoft** [comment]
Module cables are reversed. Use a thin flat blade to pull up the securing pin and swap them.

**Comment by stuartpittaway** [comment]
What is wrong with the SD card holder? Does it work okay?

**Comment by trebor1508** [comment]
It is working but screen need to be removed to install sd card.

**Comment by stuartpittaway** [comment]
> It is working but screen need to be removed to install sd card.

That's a relief, I've ordered 40 boards!

The new card holder is more secure, and the card won't fall out due to vibration etc.

**Comment by trebor1508** [comment]
To be clear,  i am not complaining. I am sharing my thoughts and observations.

**Comment by stuartpittaway** [comment]
No problem, I didn't read it as a complaint, just making sure it all works!!

**Comment by trebor1508** [comment]
Good. I will do some modules and seehow it works with them.

**Comment by trebor1508** [comment]
![Screenshot_2021-06-03-13-46-31](https://user-images.githubusercontent.com/77877722/120647252-4e113b00-c472-11eb-9ce8-15df3383b83c.jpg)
So this plus belong to connector? I think i bought wrong cable.

**Comment by atanisoft** [comment]
> So this plus belong to connector? I think i bought wrong cable.

Yes, the red/black need to be reversed in the cable. Unfortunately almost all cables are sold in this fashion. You can use a thin blade to pull up the locking pin on the cable to remove the wires and reinsert them in the correct orientation.

**Comment by trebor1508** [comment]
what mean "libusb0.dll" can not be found? I try to program module.

**Comment by shampeon** [comment]
> Parts which can be used:
> 
> IFX1050GXUMA1 = C129255
> TJA1057GT/3J = C112947
> TJA1051TK/3 (no longer available from JLCPCB)
> 
> On the TJA range - the import part is the "/3" - indicating its 3.3V compatible.
> 
> At the time of writing, JLC have very little stock of the above.
> 
> Looking at other sites, all are out of stock (Farnell/Mouser etc.)
> 

Would this TI chip be a good replacement for the TJA1057GT/3J? Mouser has plenty in stock. 
https://www.mouser.com/ProductDetail/Texas-Instruments/TCAN4420DR?qs=W0yvOO0ixfFdDbLci2afMw%3D%3D

**Comment by atanisoft** [comment]
@shampeon from a very quick review of the datasheet it looks like it might work. It does have a considerably higher cost basis though, around 3x of TJA1057GT/3J and 2x of IFX1050GXUMA1.

**Comment by fhorst1** [comment]
At $2.72 total price will be 2 bucks more, per module.

For low cost, the older controller board works fine.

For more (future) advanced controller, the 2 bucks extra is probably not going to be the showstopper.

I found with my order Many parts unavailable from JLCPCB, and just ordered with what was available.
The rest via components shop like Rs-online.

**Comment by stuartpittaway** [comment]
As the CAN chip is not used at the moment, I'd wait and add the correct part when available

**Comment by trebor1508** [comment]
Up to what voltage cell modules can be safely connected?

**Comment by phisp** [comment]
i tried 6V with the V4.00 and the leds got very bright but it worked. According to the Attiny Datasheet: 1.7-5.5v, however the Optocoupler and the Leds will fail probably first. Voltages below the referance Voltage will result in false measurements. And some boards started to balance the cells. Somehow you could program the Attiny to shutdown, if the voltage is getting to low, however i was not able to find it.

**Comment by stuartpittaway** [comment]
> Up to what voltage cell modules can be safely connected?

The modules are designed for maximum of 4.35V, but most of the components work to 5V maximum

**Comment by trebor1508** [comment]
> > Up to what voltage cell modules can be safely connected?
> 
> The modules are designed for maximum of 4.35V, but most of the components work to 5V maximum
> 
> The attiny is programmed to shutdown at 1.8V

Do you think about modules to work with leisure batteries in campers for example?

**Comment by stuartpittaway** [comment]
Is there a need? Lead acid don't need balance, the new current monitor (out soon!) would measure voltage as well (up to 85v).

**Comment by trebor1508** [comment]
When i can change numbers of modules settings before i connect them to controler with loop RX TX? Or modules should be connected and changing setting then? I see "failed to save settings"

**Comment by stuartpittaway** [comment]
Just press F5 to refresh the webpage if you see the save error.

**Comment by trebor1508** [comment]
![20210609_225457](https://user-images.githubusercontent.com/77877722/121434817-ca75b380-c975-11eb-9a07-f0f117e7b050.jpg)
Why this is happening?

**Comment by stuartpittaway** [comment]
It can't talk to the attiny chip in the module, have you connected it correctly to the ISP header?

**Comment by trebor1508** [comment]
Yes.

**Comment by trebor1508** [comment]
![1623276632634256663728](https://user-images.githubusercontent.com/77877722/121436136-ee39f900-c977-11eb-83d4-4edc0bf10af2.jpg)
And 1 module have incorrect voltage readings.

**Comment by stuartpittaway** [comment]
Have you calibrated the modules?  Switch off balancing before calibration though

**Comment by trebor1508** [comment]
> Have you calibrated the modules? Switch off balancing before calibration though

I am so sorry but i have watched all your youtube films and tried to find on forum how to do that but i have no idea.

**Comment by stuartpittaway** [comment]
You need to calibrate each module against the cell using a good quality known accurate multimeter.

Measure the voltage of the cell (when idle/not balancing or charging) and enter it into the module page, configuration setting.


Until then, the cell voltages will vary.

**Comment by trebor1508** [comment]
It works. Thanks.
And how to switch off balancing?

**Comment by stuartpittaway** [comment]
Balancing stops when the voltage is lower than the balance voltage set in the web interface.

If the modules are going into bypass straight away, try and calibrate with a different cell at a lower voltage

**Comment by SergioRius** [comment]
On to the TJA1057GT/3J topic, do something need to be done to the jumper pad near the top of the can chip, or is totally unrelated?
I have this pad without solder and I'm afraid is something necessary for the TJA1057GT/3J to work.

**Comment by SergioRius** [comment]
> @SergioRius
> 
> > do something need to be done to the jumper pad near the top of the can chip, or is totally unrelated?
> 
> The jumper selects the CAN bus voltage (5v or 3v3) and defaults to 5v which is the most common CAN voltage. IF the hardware you are connecting to uses 3v3 CAN voltage you can cut the trace between the center pad and the 5v pad and then add a solder blob to connect the center pad to the 3v3 pad. But likely you can leave it as-is.

Thanks, i didn't appreciate a track between 5v pads.
