### ISSUE TITLE
what mean "libusb0.dll" can not be found? I try to program module.

### ISSUE THREAD

**Issue by stuartpittaway** [stuartpittaway/diyBMSv4#86]
what mean "libusb0.dll" can not be found? I try to program module.

_Originally posted by @trebor1508 in https://github.com/stuartpittaway/diyBMSv4/issues/83#issuecomment-854210283_

**Comment by stuartpittaway** [comment]
Is this when using avrdude?

**Comment by trebor1508** [comment]
Yes. But i have used avr programmer on new controller. Successful.

**Comment by fhorst1** [comment]
Not all things are equal, 

The controller board is esp32
Cell modules attiny

Different libraries are used.

Your computer seems to be missing libusb0.dll

Easy enough to fix, Google is your friend.

Of YouTube :-)
https://youtu.be/zbDJUOoGnYs
