### ISSUE TITLE
Problem stock integrated circuits Texas instruments

### ISSUE THREAD

**Issue by alfmalo000** [stuartpittaway/diyBMSv4#99]
Hi.
I want to order to JLPCB one new controller but there are several chips that no stock and the stock will take time to appear.
This chips are:
- TCA6408APWR
- TCA9534APWR
- 
My question is, this chips are compatible  each other?:

Compatible    -->       Original
PCAL6408APWJ --> TCA6408APWR
 ???????              --> TCA9534APWR

Thanks in advance.
Best Regards

**Comment by stuartpittaway** [comment]
I don't have any way to confirm/test the replacement chips you suggest, so I can't help but say to try and obtain the original parts.
